#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Preparing files..." >> $monitor_file

file_providers_list="$1/outputs/file_providers_list"

echo "Creating file providers list..." >> $monitor_file

ls -1 $2/file-providers/ > $file_providers_list

echo "Finished" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"
