package net.sf.regadb.db;

// Generated 9/01/2007 13:30:52 by Hibernate Tools 3.2.0.beta8

/**
 * AaInsertionId generated by hbm2java
 */
public class AaInsertionId implements java.io.Serializable {

    // Fields    

    private short position;

    private int aaSequenceIi;

    private short insertionOrder;

    // Constructors

    /** default constructor */
    public AaInsertionId() {
    }

    /** full constructor */
    public AaInsertionId(short position, int aaSequenceIi, short insertionOrder) {
        this.position = position;
        this.aaSequenceIi = aaSequenceIi;
        this.insertionOrder = insertionOrder;
    }

    // Property accessors
    public short getPosition() {
        return this.position;
    }

    public void setPosition(short position) {
        this.position = position;
    }

    public int getAaSequenceIi() {
        return this.aaSequenceIi;
    }

    public void setAaSequenceIi(int aaSequenceIi) {
        this.aaSequenceIi = aaSequenceIi;
    }

    public short getInsertionOrder() {
        return this.insertionOrder;
    }

    public void setInsertionOrder(short insertionOrder) {
        this.insertionOrder = insertionOrder;
    }

}
