package net.sf.regadb.db;

// Generated Jan 3, 2007 11:34:35 AM by Hibernate Tools 3.2.0.beta8

/**
 * AaMutationId generated by hbm2java
 */
public class AaMutationId implements java.io.Serializable {

    // Fields    

    private short position;

    private int aaSequenceIi;

    // Constructors

    /** default constructor */
    public AaMutationId() {
    }

    /** full constructor */
    public AaMutationId(short position, int aaSequenceIi) {
        this.position = position;
        this.aaSequenceIi = aaSequenceIi;
    }

    // Property accessors
    public short getPosition() {
        return this.position;
    }

    public void setPosition(short position) {
        this.position = position;
    }

    public int getAaSequenceIi() {
        return this.aaSequenceIi;
    }

    public void setAaSequenceIi(int aaSequenceIi) {
        this.aaSequenceIi = aaSequenceIi;
    }

}
