package net.sf.regadb.db;

// Generated Jan 11, 2007 2:11:17 PM by Hibernate Tools 3.2.0.beta8

/**
 * AaMutationId generated by hbm2java
 */
public class AaMutationId implements java.io.Serializable {

    // Fields    

    private short position;

    private AaSequence aaSequence;

    // Constructors

    /** default constructor */
    public AaMutationId() {
    }

    /** full constructor */
    public AaMutationId(short position, AaSequence aaSequence) {
        this.position = position;
        this.aaSequence = aaSequence;
    }

    // Property accessors
    public short getPosition() {
        return this.position;
    }

    public void setPosition(short position) {
        this.position = position;
    }

    public AaSequence getAaSequence() {
        return this.aaSequence;
    }

    public void setAaSequence(AaSequence aaSequence) {
        this.aaSequence = aaSequence;
    }

}
