package net.sf.regadb.db;

// Generated Jan 3, 2007 11:34:35 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * AaSequence generated by hbm2java
 */
public class AaSequence implements java.io.Serializable {

    // Fields    

    private int aaSequenceIi;

    private Integer version;

    private NtSequence ntSequence;

    private Protein protein;

    private short firstAaPos;

    private short lastAaPos;

    private Set<AaMutation> aaMutations = new HashSet<AaMutation>(0);

    private Set<AaInsertion> aaInsertions = new HashSet<AaInsertion>(0);

    // Constructors

    /** default constructor */
    public AaSequence() {
    }

    /** minimal constructor */
    public AaSequence(int aaSequenceIi, NtSequence ntSequence, Protein protein,
            short firstAaPos, short lastAaPos) {
        this.aaSequenceIi = aaSequenceIi;
        this.ntSequence = ntSequence;
        this.protein = protein;
        this.firstAaPos = firstAaPos;
        this.lastAaPos = lastAaPos;
    }

    /** full constructor */
    public AaSequence(int aaSequenceIi, NtSequence ntSequence, Protein protein,
            short firstAaPos, short lastAaPos, Set<AaMutation> aaMutations,
            Set<AaInsertion> aaInsertions) {
        this.aaSequenceIi = aaSequenceIi;
        this.ntSequence = ntSequence;
        this.protein = protein;
        this.firstAaPos = firstAaPos;
        this.lastAaPos = lastAaPos;
        this.aaMutations = aaMutations;
        this.aaInsertions = aaInsertions;
    }

    // Property accessors
    public int getAaSequenceIi() {
        return this.aaSequenceIi;
    }

    public void setAaSequenceIi(int aaSequenceIi) {
        this.aaSequenceIi = aaSequenceIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public NtSequence getNtSequence() {
        return this.ntSequence;
    }

    public void setNtSequence(NtSequence ntSequence) {
        this.ntSequence = ntSequence;
    }

    public Protein getProtein() {
        return this.protein;
    }

    public void setProtein(Protein protein) {
        this.protein = protein;
    }

    public short getFirstAaPos() {
        return this.firstAaPos;
    }

    public void setFirstAaPos(short firstAaPos) {
        this.firstAaPos = firstAaPos;
    }

    public short getLastAaPos() {
        return this.lastAaPos;
    }

    public void setLastAaPos(short lastAaPos) {
        this.lastAaPos = lastAaPos;
    }

    public Set<AaMutation> getAaMutations() {
        return this.aaMutations;
    }

    public void setAaMutations(Set<AaMutation> aaMutations) {
        this.aaMutations = aaMutations;
    }

    public Set<AaInsertion> getAaInsertions() {
        return this.aaInsertions;
    }

    public void setAaInsertions(Set<AaInsertion> aaInsertions) {
        this.aaInsertions = aaInsertions;
    }

}
