package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

/**
 * AaSequence generated by hbm2java
 */
public class AaSequence implements java.io.Serializable {

    // Fields    

    private Integer aaSequenceIi;

    private Integer version;

    private NtSequence ntSequence;

    private Protein protein;

    private short firstAaPos;

    private short lastAaPos;

    // Constructors

    /** default constructor */
    public AaSequence() {
    }

    /** full constructor */
    public AaSequence(NtSequence ntSequence, Protein protein, short firstAaPos,
            short lastAaPos) {
        this.ntSequence = ntSequence;
        this.protein = protein;
        this.firstAaPos = firstAaPos;
        this.lastAaPos = lastAaPos;
    }

    // Property accessors
    public Integer getAaSequenceIi() {
        return this.aaSequenceIi;
    }

    public void setAaSequenceIi(Integer aaSequenceIi) {
        this.aaSequenceIi = aaSequenceIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public NtSequence getNtSequence() {
        return this.ntSequence;
    }

    public void setNtSequence(NtSequence ntSequence) {
        this.ntSequence = ntSequence;
    }

    public Protein getProtein() {
        return this.protein;
    }

    public void setProtein(Protein protein) {
        this.protein = protein;
    }

    public short getFirstAaPos() {
        return this.firstAaPos;
    }

    public void setFirstAaPos(short firstAaPos) {
        this.firstAaPos = firstAaPos;
    }

    public short getLastAaPos() {
        return this.lastAaPos;
    }

    public void setLastAaPos(short lastAaPos) {
        this.lastAaPos = lastAaPos;
    }

}
