package net.sf.regadb.db;

// Generated Jan 3, 2007 11:34:35 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute implements java.io.Serializable {

    // Fields    

    private int attributeIi;

    private Integer version;

    private ValueType valueType;

    private String name;

    private Boolean patientAttribute;

    private Boolean sequenceAttribute;

    private Set<AttributeNominalValue> attributeNominalValues = new HashSet<AttributeNominalValue>(
            0);

    private Set<PatientAttributeValue> patientAttributeValues = new HashSet<PatientAttributeValue>(
            0);

    // Constructors

    /** default constructor */
    public Attribute() {
    }

    /** minimal constructor */
    public Attribute(int attributeIi, String name) {
        this.attributeIi = attributeIi;
        this.name = name;
    }

    /** full constructor */
    public Attribute(int attributeIi, ValueType valueType, String name,
            Boolean patientAttribute, Boolean sequenceAttribute,
            Set<AttributeNominalValue> attributeNominalValues,
            Set<PatientAttributeValue> patientAttributeValues) {
        this.attributeIi = attributeIi;
        this.valueType = valueType;
        this.name = name;
        this.patientAttribute = patientAttribute;
        this.sequenceAttribute = sequenceAttribute;
        this.attributeNominalValues = attributeNominalValues;
        this.patientAttributeValues = patientAttributeValues;
    }

    // Property accessors
    public int getAttributeIi() {
        return this.attributeIi;
    }

    public void setAttributeIi(int attributeIi) {
        this.attributeIi = attributeIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public ValueType getValueType() {
        return this.valueType;
    }

    public void setValueType(ValueType valueType) {
        this.valueType = valueType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getPatientAttribute() {
        return this.patientAttribute;
    }

    public void setPatientAttribute(Boolean patientAttribute) {
        this.patientAttribute = patientAttribute;
    }

    public Boolean getSequenceAttribute() {
        return this.sequenceAttribute;
    }

    public void setSequenceAttribute(Boolean sequenceAttribute) {
        this.sequenceAttribute = sequenceAttribute;
    }

    public Set<AttributeNominalValue> getAttributeNominalValues() {
        return this.attributeNominalValues;
    }

    public void setAttributeNominalValues(
            Set<AttributeNominalValue> attributeNominalValues) {
        this.attributeNominalValues = attributeNominalValues;
    }

    public Set<PatientAttributeValue> getPatientAttributeValues() {
        return this.patientAttributeValues;
    }

    public void setPatientAttributeValues(
            Set<PatientAttributeValue> patientAttributeValues) {
        this.patientAttributeValues = patientAttributeValues;
    }

}
