package net.sf.regadb.db;

// Generated Jan 11, 2007 1:17:53 PM by Hibernate Tools 3.2.0.beta8

/**
 * AttributeNominalValueId generated by hbm2java
 */
public class AttributeNominalValueId implements java.io.Serializable {

    // Fields    

    private int nominalValueIi;

    private int attributeIi;

    // Constructors

    /** default constructor */
    public AttributeNominalValueId() {
    }

    /** full constructor */
    public AttributeNominalValueId(int nominalValueIi, int attributeIi) {
        this.nominalValueIi = nominalValueIi;
        this.attributeIi = attributeIi;
    }

    // Property accessors
    public int getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(int nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

    public int getAttributeIi() {
        return this.attributeIi;
    }

    public void setAttributeIi(int attributeIi) {
        this.attributeIi = attributeIi;
    }

}
