package net.sf.regadb.db;

// Generated Jan 11, 2007 2:11:17 PM by Hibernate Tools 3.2.0.beta8

/**
 * AttributeNominalValue generated by hbm2java
 */
public class AttributeNominalValue implements java.io.Serializable {

    // Fields    

    private Integer nominalValueIi;

    private Integer version;

    private Attribute attribute;

    private String value;

    // Constructors

    /** default constructor */
    public AttributeNominalValue() {
    }

    /** full constructor */
    public AttributeNominalValue(Attribute attribute, String value) {
        this.attribute = attribute;
        this.value = value;
    }

    // Property accessors
    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
