package net.sf.regadb.db;

// Generated Jan 3, 2007 4:02:11 PM by Hibernate Tools 3.2.0.beta8

/**
 * DatasetAccessId generated by hbm2java
 */
public class DatasetAccessId implements java.io.Serializable {

    // Fields    

    private String uid;

    private int datasetIi;

    // Constructors

    /** default constructor */
    public DatasetAccessId() {
    }

    /** full constructor */
    public DatasetAccessId(String uid, int datasetIi) {
        this.uid = uid;
        this.datasetIi = datasetIi;
    }

    // Property accessors
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public int getDatasetIi() {
        return this.datasetIi;
    }

    public void setDatasetIi(int datasetIi) {
        this.datasetIi = datasetIi;
    }

}
