package net.sf.regadb.db;

// Generated Jan 3, 2007 11:34:35 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * DrugCommercial generated by hbm2java
 */
public class DrugCommercial implements java.io.Serializable {

    // Fields    

    private int commercialIi;

    private Integer version;

    private String name;

    private Set<DrugGeneric> drugGenerics = new HashSet<DrugGeneric>(0);

    private Set<TherapyCommercial> therapyCommercials = new HashSet<TherapyCommercial>(
            0);

    // Constructors

    /** default constructor */
    public DrugCommercial() {
    }

    /** minimal constructor */
    public DrugCommercial(int commercialIi, String name) {
        this.commercialIi = commercialIi;
        this.name = name;
    }

    /** full constructor */
    public DrugCommercial(int commercialIi, String name,
            Set<DrugGeneric> drugGenerics,
            Set<TherapyCommercial> therapyCommercials) {
        this.commercialIi = commercialIi;
        this.name = name;
        this.drugGenerics = drugGenerics;
        this.therapyCommercials = therapyCommercials;
    }

    // Property accessors
    public int getCommercialIi() {
        return this.commercialIi;
    }

    public void setCommercialIi(int commercialIi) {
        this.commercialIi = commercialIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<DrugGeneric> getDrugGenerics() {
        return this.drugGenerics;
    }

    public void setDrugGenerics(Set<DrugGeneric> drugGenerics) {
        this.drugGenerics = drugGenerics;
    }

    public Set<TherapyCommercial> getTherapyCommercials() {
        return this.therapyCommercials;
    }

    public void setTherapyCommercials(Set<TherapyCommercial> therapyCommercials) {
        this.therapyCommercials = therapyCommercials;
    }

}
