package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * DrugCommercial generated by hbm2java
 */
public class DrugCommercial implements java.io.Serializable {

    // Fields    

    private Integer commercialIi;

    private Integer version;

    private String name;

    private Set<DrugGeneric> drugGenerics = new HashSet<DrugGeneric>(0);

    // Constructors

    /** default constructor */
    public DrugCommercial() {
    }

    /** minimal constructor */
    public DrugCommercial(String name) {
        this.name = name;
    }

    /** full constructor */
    public DrugCommercial(String name, Set<DrugGeneric> drugGenerics) {
        this.name = name;
        this.drugGenerics = drugGenerics;
    }

    // Property accessors
    public Integer getCommercialIi() {
        return this.commercialIi;
    }

    public void setCommercialIi(Integer commercialIi) {
        this.commercialIi = commercialIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<DrugGeneric> getDrugGenerics() {
        return this.drugGenerics;
    }

    public void setDrugGenerics(Set<DrugGeneric> drugGenerics) {
        this.drugGenerics = drugGenerics;
    }

}
