package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender implements java.io.Serializable {

    // Fields    

    private int genderIi;

    private Integer version;

    private String description;

    private Set<Patient> patients = new HashSet<Patient>(0);

    // Constructors

    /** default constructor */
    public Gender() {
    }

    /** minimal constructor */
    public Gender(int genderIi) {
        this.genderIi = genderIi;
    }

    /** full constructor */
    public Gender(int genderIi, String description, Set<Patient> patients) {
        this.genderIi = genderIi;
        this.description = description;
        this.patients = patients;
    }

    // Property accessors
    public int getGenderIi() {
        return this.genderIi;
    }

    public void setGenderIi(int genderIi) {
        this.genderIi = genderIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Patient> getPatients() {
        return this.patients;
    }

    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }

}
