package net.sf.regadb.db;

// Generated 9/01/2007 13:30:52 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * NtSequence generated by hbm2java
 */
public class NtSequence implements java.io.Serializable {

    // Fields    

    private Integer ntSequenceIi;

    private Integer version;

    private ViralIsolate viralIsolate;

    private String nucleotides;

    private String hivType;

    private String hivSubtype;

    private Set<AaSequence> aaSequences = new HashSet<AaSequence>(0);

    // Constructors

    /** default constructor */
    public NtSequence() {
    }

    /** minimal constructor */
    public NtSequence(ViralIsolate viralIsolate) {
        this.viralIsolate = viralIsolate;
    }

    /** full constructor */
    public NtSequence(ViralIsolate viralIsolate, String nucleotides,
            String hivType, String hivSubtype, Set<AaSequence> aaSequences) {
        this.viralIsolate = viralIsolate;
        this.nucleotides = nucleotides;
        this.hivType = hivType;
        this.hivSubtype = hivSubtype;
        this.aaSequences = aaSequences;
    }

    // Property accessors
    public Integer getNtSequenceIi() {
        return this.ntSequenceIi;
    }

    public void setNtSequenceIi(Integer ntSequenceIi) {
        this.ntSequenceIi = ntSequenceIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public ViralIsolate getViralIsolate() {
        return this.viralIsolate;
    }

    public void setViralIsolate(ViralIsolate viralIsolate) {
        this.viralIsolate = viralIsolate;
    }

    public String getNucleotides() {
        return this.nucleotides;
    }

    public void setNucleotides(String nucleotides) {
        this.nucleotides = nucleotides;
    }

    public String getHivType() {
        return this.hivType;
    }

    public void setHivType(String hivType) {
        this.hivType = hivType;
    }

    public String getHivSubtype() {
        return this.hivSubtype;
    }

    public void setHivSubtype(String hivSubtype) {
        this.hivSubtype = hivSubtype;
    }

    public Set<AaSequence> getAaSequences() {
        return this.aaSequences;
    }

    public void setAaSequences(Set<AaSequence> aaSequences) {
        this.aaSequences = aaSequences;
    }

}
