package net.sf.regadb.db;

// Generated 18/01/2007 18:32:09 by Hibernate Tools 3.2.0.beta8

/**
 * PatientAttributeValue generated by hbm2java
 */
public class PatientAttributeValue implements java.io.Serializable {

    // Fields    

    private PatientAttributeValueId id;

    private Integer version;

    private Attribute attribute;

    private PatientImpl patient;

    private AttributeNominalValue attributeNominalValue;

    private String value;

    // Constructors

    /** default constructor */
    public PatientAttributeValue() {
    }

    /** minimal constructor */
    public PatientAttributeValue(PatientAttributeValueId id,
            Attribute attribute, PatientImpl patient) {
        this.id = id;
        this.attribute = attribute;
        this.patient = patient;
    }

    /** full constructor */
    public PatientAttributeValue(PatientAttributeValueId id,
            Attribute attribute, PatientImpl patient,
            AttributeNominalValue attributeNominalValue, String value) {
        this.id = id;
        this.attribute = attribute;
        this.patient = patient;
        this.attributeNominalValue = attributeNominalValue;
        this.value = value;
    }

    // Property accessors
    public PatientAttributeValueId getId() {
        return this.id;
    }

    public void setId(PatientAttributeValueId id) {
        this.id = id;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public AttributeNominalValue getAttributeNominalValue() {
        return this.attributeNominalValue;
    }

    public void setAttributeNominalValue(
            AttributeNominalValue attributeNominalValue) {
        this.attributeNominalValue = attributeNominalValue;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
