package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

    // Fields    

    private int patientIi;

    private Integer version;

    private Gender gender;

    private String patientId;

    private String lastName;

    private String firstName;

    private Date birthDate;

    private Date deathDate;

    private Set<Dataset> datasets = new HashSet<Dataset>(0);

    private Set<TestResult> testResults = new HashSet<TestResult>(0);

    private Set<PatientAttributeValue> patientAttributeValues = new HashSet<PatientAttributeValue>(
            0);

    private Set<ViralIsolate> viralIsolates = new HashSet<ViralIsolate>(0);

    private Set<Therapy> therapies = new HashSet<Therapy>(0);

    // Constructors

    /** default constructor */
    public Patient() {
    }

    /** minimal constructor */
    public Patient(int patientIi, String patientId) {
        this.patientIi = patientIi;
        this.patientId = patientId;
    }

    /** full constructor */
    public Patient(int patientIi, Gender gender, String patientId,
            String lastName, String firstName, Date birthDate, Date deathDate,
            Set<Dataset> datasets, Set<TestResult> testResults,
            Set<PatientAttributeValue> patientAttributeValues,
            Set<ViralIsolate> viralIsolates, Set<Therapy> therapies) {
        this.patientIi = patientIi;
        this.gender = gender;
        this.patientId = patientId;
        this.lastName = lastName;
        this.firstName = firstName;
        this.birthDate = birthDate;
        this.deathDate = deathDate;
        this.datasets = datasets;
        this.testResults = testResults;
        this.patientAttributeValues = patientAttributeValues;
        this.viralIsolates = viralIsolates;
        this.therapies = therapies;
    }

    // Property accessors
    public int getPatientIi() {
        return this.patientIi;
    }

    public void setPatientIi(int patientIi) {
        this.patientIi = patientIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getPatientId() {
        return this.patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public Date getDeathDate() {
        return this.deathDate;
    }

    public void setDeathDate(Date deathDate) {
        this.deathDate = deathDate;
    }

    Set<Dataset> getDatasets() {
        return this.datasets;
    }

    void setDatasets(Set<Dataset> datasets) {
        this.datasets = datasets;
    }

    public Set<TestResult> getTestResults() {
        return this.testResults;
    }

    public void setTestResults(Set<TestResult> testResults) {
        this.testResults = testResults;
    }

    public Set<PatientAttributeValue> getPatientAttributeValues() {
        return this.patientAttributeValues;
    }

    public void setPatientAttributeValues(
            Set<PatientAttributeValue> patientAttributeValues) {
        this.patientAttributeValues = patientAttributeValues;
    }

    public Set<ViralIsolate> getViralIsolates() {
        return this.viralIsolates;
    }

    public void setViralIsolates(Set<ViralIsolate> viralIsolates) {
        this.viralIsolates = viralIsolates;
    }

    public Set<Therapy> getTherapies() {
        return this.therapies;
    }

    public void setTherapies(Set<Therapy> therapies) {
        this.therapies = therapies;
    }

}
