package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

/**
 * PatientAttributeValue generated by hbm2java
 */
public class PatientAttributeValue implements java.io.Serializable {

    // Fields    

    private PatientAttributeValueId id;

    private Integer version;

    private Attribute attribute;

    private Patient patient;

    private String value;

    private Integer nominalValueIi;

    // Constructors

    /** default constructor */
    public PatientAttributeValue() {
    }

    /** minimal constructor */
    public PatientAttributeValue(PatientAttributeValueId id,
            Attribute attribute, Patient patient) {
        this.id = id;
        this.attribute = attribute;
        this.patient = patient;
    }

    /** full constructor */
    public PatientAttributeValue(PatientAttributeValueId id,
            Attribute attribute, Patient patient, String value,
            Integer nominalValueIi) {
        this.id = id;
        this.attribute = attribute;
        this.patient = patient;
        this.value = value;
        this.nominalValueIi = nominalValueIi;
    }

    // Property accessors
    public PatientAttributeValueId getId() {
        return this.id;
    }

    public void setId(PatientAttributeValueId id) {
        this.id = id;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

}
