package net.sf.regadb.db;

// Generated 22/01/2007 12:43:36 by Hibernate Tools 3.2.0.beta8

/**
 * PatientAttributeValueId generated by hbm2java
 */
public class PatientAttributeValueId implements java.io.Serializable {

    // Fields    

    private PatientImpl patient;

    private Attribute attribute;

    // Constructors

    /** default constructor */
    public PatientAttributeValueId() {
    }

    /** full constructor */
    public PatientAttributeValueId(PatientImpl patient, Attribute attribute) {
        this.patient = patient;
        this.attribute = attribute;
    }

    // Property accessors
    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

}
