package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Protein generated by hbm2java
 */
public class Protein implements java.io.Serializable {

    // Fields    

    private int proteinIi;

    private Integer version;

    private String abbreviation;

    private String fullName;

    private Set<AaSequence> aaSequences = new HashSet<AaSequence>(0);

    // Constructors

    /** default constructor */
    public Protein() {
    }

    /** minimal constructor */
    public Protein(int proteinIi, String abbreviation) {
        this.proteinIi = proteinIi;
        this.abbreviation = abbreviation;
    }

    /** full constructor */
    public Protein(int proteinIi, String abbreviation, String fullName,
            Set<AaSequence> aaSequences) {
        this.proteinIi = proteinIi;
        this.abbreviation = abbreviation;
        this.fullName = fullName;
        this.aaSequences = aaSequences;
    }

    // Property accessors
    public int getProteinIi() {
        return this.proteinIi;
    }

    public void setProteinIi(int proteinIi) {
        this.proteinIi = proteinIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getAbbreviation() {
        return this.abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Set<AaSequence> getAaSequences() {
        return this.aaSequences;
    }

    public void setAaSequences(Set<AaSequence> aaSequences) {
        this.aaSequences = aaSequences;
    }

}
