package net.sf.regadb.db;

// Generated Jan 3, 2007 11:34:35 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

    // Fields    

    private int testIi;

    private Integer version;

    private TestType testType;

    private String description;

    private String serviceClass;

    private String serviceData;

    private String serviceConfig;

    private Set<TestResult> testResults = new HashSet<TestResult>(0);

    private Set<SettingsUser> settingsUsers = new HashSet<SettingsUser>(0);

    // Constructors

    /** default constructor */
    public Test() {
    }

    /** minimal constructor */
    public Test(int testIi, TestType testType, String description) {
        this.testIi = testIi;
        this.testType = testType;
        this.description = description;
    }

    /** full constructor */
    public Test(int testIi, TestType testType, String description,
            String serviceClass, String serviceData, String serviceConfig,
            Set<TestResult> testResults, Set<SettingsUser> settingsUsers) {
        this.testIi = testIi;
        this.testType = testType;
        this.description = description;
        this.serviceClass = serviceClass;
        this.serviceData = serviceData;
        this.serviceConfig = serviceConfig;
        this.testResults = testResults;
        this.settingsUsers = settingsUsers;
    }

    // Property accessors
    public int getTestIi() {
        return this.testIi;
    }

    public void setTestIi(int testIi) {
        this.testIi = testIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public TestType getTestType() {
        return this.testType;
    }

    public void setTestType(TestType testType) {
        this.testType = testType;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getServiceClass() {
        return this.serviceClass;
    }

    public void setServiceClass(String serviceClass) {
        this.serviceClass = serviceClass;
    }

    public String getServiceData() {
        return this.serviceData;
    }

    public void setServiceData(String serviceData) {
        this.serviceData = serviceData;
    }

    public String getServiceConfig() {
        return this.serviceConfig;
    }

    public void setServiceConfig(String serviceConfig) {
        this.serviceConfig = serviceConfig;
    }

    public Set<TestResult> getTestResults() {
        return this.testResults;
    }

    public void setTestResults(Set<TestResult> testResults) {
        this.testResults = testResults;
    }

    public Set<SettingsUser> getSettingsUsers() {
        return this.settingsUsers;
    }

    public void setSettingsUsers(Set<SettingsUser> settingsUsers) {
        this.settingsUsers = settingsUsers;
    }

}
