package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

/**
 * TestNominalValue generated by hbm2java
 */
public class TestNominalValue implements java.io.Serializable {

    // Fields    

    private Integer nominalValueIi;

    private Integer version;

    private TestType testType;

    private String value;

    // Constructors

    /** default constructor */
    public TestNominalValue() {
    }

    /** full constructor */
    public TestNominalValue(TestType testType, String value) {
        this.testType = testType;
        this.value = value;
    }

    // Property accessors
    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public TestType getTestType() {
        return this.testType;
    }

    public void setTestType(TestType testType) {
        this.testType = testType;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
