package net.sf.regadb.db;

// Generated Jan 11, 2007 2:11:17 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * TestResult generated by hbm2java
 */
public class TestResult implements java.io.Serializable {

    // Fields    

    private Integer testResultIi;

    private Integer version;

    private Test test;

    private DrugGeneric drugGeneric;

    private ViralIsolate viralIsolate;

    private PatientImpl patient;

    private String value;

    private Date testDate;

    private String sampleId;

    private Integer nominalValueIi;

    // Constructors

    /** default constructor */
    public TestResult() {
    }

    /** minimal constructor */
    public TestResult(Test test, PatientImpl patient) {
        this.test = test;
        this.patient = patient;
    }

    /** full constructor */
    public TestResult(Test test, DrugGeneric drugGeneric,
            ViralIsolate viralIsolate, PatientImpl patient, String value,
            Date testDate, String sampleId, Integer nominalValueIi) {
        this.test = test;
        this.drugGeneric = drugGeneric;
        this.viralIsolate = viralIsolate;
        this.patient = patient;
        this.value = value;
        this.testDate = testDate;
        this.sampleId = sampleId;
        this.nominalValueIi = nominalValueIi;
    }

    // Property accessors
    public Integer getTestResultIi() {
        return this.testResultIi;
    }

    public void setTestResultIi(Integer testResultIi) {
        this.testResultIi = testResultIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Test getTest() {
        return this.test;
    }

    public void setTest(Test test) {
        this.test = test;
    }

    public DrugGeneric getDrugGeneric() {
        return this.drugGeneric;
    }

    public void setDrugGeneric(DrugGeneric drugGeneric) {
        this.drugGeneric = drugGeneric;
    }

    public ViralIsolate getViralIsolate() {
        return this.viralIsolate;
    }

    public void setViralIsolate(ViralIsolate viralIsolate) {
        this.viralIsolate = viralIsolate;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getTestDate() {
        return this.testDate;
    }

    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    public String getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

}
