package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * TestObject generated by hbm2java
 */
public class TestObject implements java.io.Serializable {

    // Fields    

    private int testObjectIi;

    private Integer version;

    private String description;

    private Set<TestType> testTypes = new HashSet<TestType>(0);

    // Constructors

    /** default constructor */
    public TestObject() {
    }

    /** minimal constructor */
    public TestObject(int testObjectIi, String description) {
        this.testObjectIi = testObjectIi;
        this.description = description;
    }

    /** full constructor */
    public TestObject(int testObjectIi, String description,
            Set<TestType> testTypes) {
        this.testObjectIi = testObjectIi;
        this.description = description;
        this.testTypes = testTypes;
    }

    // Property accessors
    public int getTestObjectIi() {
        return this.testObjectIi;
    }

    public void setTestObjectIi(int testObjectIi) {
        this.testObjectIi = testObjectIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<TestType> getTestTypes() {
        return this.testTypes;
    }

    public void setTestTypes(Set<TestType> testTypes) {
        this.testTypes = testTypes;
    }

}
