package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * TestType generated by hbm2java
 */
public class TestType implements java.io.Serializable {

    // Fields    

    private int testTypeIi;

    private Integer version;

    private ValueType valueType;

    private TestObject testObject;

    private String description;

    private Set<Test> tests = new HashSet<Test>(0);

    private Set<TestNominalValue> testNominalValues = new HashSet<TestNominalValue>(
            0);

    // Constructors

    /** default constructor */
    public TestType() {
    }

    /** minimal constructor */
    public TestType(int testTypeIi, TestObject testObject, String description) {
        this.testTypeIi = testTypeIi;
        this.testObject = testObject;
        this.description = description;
    }

    /** full constructor */
    public TestType(int testTypeIi, ValueType valueType, TestObject testObject,
            String description, Set<Test> tests,
            Set<TestNominalValue> testNominalValues) {
        this.testTypeIi = testTypeIi;
        this.valueType = valueType;
        this.testObject = testObject;
        this.description = description;
        this.tests = tests;
        this.testNominalValues = testNominalValues;
    }

    // Property accessors
    public int getTestTypeIi() {
        return this.testTypeIi;
    }

    public void setTestTypeIi(int testTypeIi) {
        this.testTypeIi = testTypeIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public ValueType getValueType() {
        return this.valueType;
    }

    public void setValueType(ValueType valueType) {
        this.valueType = valueType;
    }

    public TestObject getTestObject() {
        return this.testObject;
    }

    public void setTestObject(TestObject testObject) {
        this.testObject = testObject;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Test> getTests() {
        return this.tests;
    }

    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }

    public Set<TestNominalValue> getTestNominalValues() {
        return this.testNominalValues;
    }

    public void setTestNominalValues(Set<TestNominalValue> testNominalValues) {
        this.testNominalValues = testNominalValues;
    }

}
