package net.sf.regadb.db;

// Generated 9/01/2007 13:30:52 by Hibernate Tools 3.2.0.beta8

/**
 * TherapyCommercialId generated by hbm2java
 */
public class TherapyCommercialId implements java.io.Serializable {

    // Fields    

    private int therapyIi;

    private int commercialIi;

    // Constructors

    /** default constructor */
    public TherapyCommercialId() {
    }

    /** full constructor */
    public TherapyCommercialId(int therapyIi, int commercialIi) {
        this.therapyIi = therapyIi;
        this.commercialIi = commercialIi;
    }

    // Property accessors
    public int getTherapyIi() {
        return this.therapyIi;
    }

    public void setTherapyIi(int therapyIi) {
        this.therapyIi = therapyIi;
    }

    public int getCommercialIi() {
        return this.commercialIi;
    }

    public void setCommercialIi(int commercialIi) {
        this.commercialIi = commercialIi;
    }

}
