package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Therapy generated by hbm2java
 */
public class Therapy implements java.io.Serializable {

    // Fields    

    private Integer therapyIi;

    private Integer version;

    private PatientImpl patient;

    private Date startDate;

    private Date stopDate;

    private String comment;

    // Constructors

    /** default constructor */
    public Therapy() {
    }

    /** minimal constructor */
    public Therapy(PatientImpl patient, Date startDate) {
        this.patient = patient;
        this.startDate = startDate;
    }

    /** full constructor */
    public Therapy(PatientImpl patient, Date startDate, Date stopDate,
            String comment) {
        this.patient = patient;
        this.startDate = startDate;
        this.stopDate = stopDate;
        this.comment = comment;
    }

    // Property accessors
    public Integer getTherapyIi() {
        return this.therapyIi;
    }

    public void setTherapyIi(Integer therapyIi) {
        this.therapyIi = therapyIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStopDate() {
        return this.stopDate;
    }

    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
