package net.sf.regadb.db;

// Generated Jan 11, 2007 2:11:17 PM by Hibernate Tools 3.2.0.beta8

/**
 * TherapyGenericId generated by hbm2java
 */
public class TherapyGenericId implements java.io.Serializable {

    // Fields    

    private Therapy therapy;

    private DrugGeneric drugGeneric;

    // Constructors

    /** default constructor */
    public TherapyGenericId() {
    }

    /** full constructor */
    public TherapyGenericId(Therapy therapy, DrugGeneric drugGeneric) {
        this.therapy = therapy;
        this.drugGeneric = drugGeneric;
    }

    // Property accessors
    public Therapy getTherapy() {
        return this.therapy;
    }

    public void setTherapy(Therapy therapy) {
        this.therapy = therapy;
    }

    public DrugGeneric getDrugGeneric() {
        return this.drugGeneric;
    }

    public void setDrugGeneric(DrugGeneric drugGeneric) {
        this.drugGeneric = drugGeneric;
    }

}
