package net.sf.regadb.db;

// Generated 9/01/2007 13:30:52 by Hibernate Tools 3.2.0.beta8

/**
 * TherapyDrugsId generated by hbm2java
 */
public class TherapyDrugsId implements java.io.Serializable {

    // Fields    

    private Integer therapyIi;

    private String drugs;

    // Constructors

    /** default constructor */
    public TherapyDrugsId() {
    }

    /** full constructor */
    public TherapyDrugsId(Integer therapyIi, String drugs) {
        this.therapyIi = therapyIi;
        this.drugs = drugs;
    }

    // Property accessors
    public Integer getTherapyIi() {
        return this.therapyIi;
    }

    public void setTherapyIi(Integer therapyIi) {
        this.therapyIi = therapyIi;
    }

    public String getDrugs() {
        return this.drugs;
    }

    public void setDrugs(String drugs) {
        this.drugs = drugs;
    }

}
