package net.sf.regadb.db;

// Generated 9/01/2007 13:30:52 by Hibernate Tools 3.2.0.beta8

/**
 * TherapyDrugs generated by hbm2java
 */
public class TherapyDrugs implements java.io.Serializable {

    // Fields    

    private TherapyDrugsId id;

    // Constructors

    /** default constructor */
    public TherapyDrugs() {
    }

    /** full constructor */
    public TherapyDrugs(TherapyDrugsId id) {
        this.id = id;
    }

    // Property accessors
    public TherapyDrugsId getId() {
        return this.id;
    }

    public void setId(TherapyDrugsId id) {
        this.id = id;
    }

}
