package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

/**
 * TherapyGeneric generated by hbm2java
 */
public class TherapyGeneric implements java.io.Serializable {

    // Fields    

    private TherapyGenericId id;

    private Integer version;

    private Therapy therapy;

    private DrugGeneric drugGeneric;

    private Double dayDosageMg;

    // Constructors

    /** default constructor */
    public TherapyGeneric() {
    }

    /** minimal constructor */
    public TherapyGeneric(TherapyGenericId id, Therapy therapy,
            DrugGeneric drugGeneric) {
        this.id = id;
        this.therapy = therapy;
        this.drugGeneric = drugGeneric;
    }

    /** full constructor */
    public TherapyGeneric(TherapyGenericId id, Therapy therapy,
            DrugGeneric drugGeneric, Double dayDosageMg) {
        this.id = id;
        this.therapy = therapy;
        this.drugGeneric = drugGeneric;
        this.dayDosageMg = dayDosageMg;
    }

    // Property accessors
    public TherapyGenericId getId() {
        return this.id;
    }

    public void setId(TherapyGenericId id) {
        this.id = id;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Therapy getTherapy() {
        return this.therapy;
    }

    public void setTherapy(Therapy therapy) {
        this.therapy = therapy;
    }

    public DrugGeneric getDrugGeneric() {
        return this.drugGeneric;
    }

    public void setDrugGeneric(DrugGeneric drugGeneric) {
        this.drugGeneric = drugGeneric;
    }

    public Double getDayDosageMg() {
        return this.dayDosageMg;
    }

    public void setDayDosageMg(Double dayDosageMg) {
        this.dayDosageMg = dayDosageMg;
    }

}
