package net.sf.regadb.db;

// Generated Dec 15, 2006 10:15:52 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * ValueType generated by hbm2java
 */
public class ValueType implements java.io.Serializable {

    // Fields    

    private int valueTypeIi;

    private Integer version;

    private String description;

    private Double min;

    private Double max;

    private Boolean multiple;

    private Set<Attribute> attributes = new HashSet<Attribute>(0);

    private Set<TestType> testTypes = new HashSet<TestType>(0);

    // Constructors

    /** default constructor */
    public ValueType() {
    }

    /** minimal constructor */
    public ValueType(int valueTypeIi, String description) {
        this.valueTypeIi = valueTypeIi;
        this.description = description;
    }

    /** full constructor */
    public ValueType(int valueTypeIi, String description, Double min,
            Double max, Boolean multiple, Set<Attribute> attributes,
            Set<TestType> testTypes) {
        this.valueTypeIi = valueTypeIi;
        this.description = description;
        this.min = min;
        this.max = max;
        this.multiple = multiple;
        this.attributes = attributes;
        this.testTypes = testTypes;
    }

    // Property accessors
    public int getValueTypeIi() {
        return this.valueTypeIi;
    }

    public void setValueTypeIi(int valueTypeIi) {
        this.valueTypeIi = valueTypeIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getMin() {
        return this.min;
    }

    public void setMin(Double min) {
        this.min = min;
    }

    public Double getMax() {
        return this.max;
    }

    public void setMax(Double max) {
        this.max = max;
    }

    public Boolean getMultiple() {
        return this.multiple;
    }

    public void setMultiple(Boolean multiple) {
        this.multiple = multiple;
    }

    public Set<Attribute> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Set<Attribute> attributes) {
        this.attributes = attributes;
    }

    public Set<TestType> getTestTypes() {
        return this.testTypes;
    }

    public void setTestTypes(Set<TestType> testTypes) {
        this.testTypes = testTypes;
    }

}
