package net.sf.regadb.db;

// Generated Jan 3, 2007 3:29:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * ViralIsolate generated by hbm2java
 */
public class ViralIsolate implements java.io.Serializable {

    // Fields    

    private Integer viralIsolateIi;

    private Integer version;

    private PatientImpl patient;

    private String sampleId;

    private Date sampleDate;

    // Constructors

    /** default constructor */
    public ViralIsolate() {
    }

    /** minimal constructor */
    public ViralIsolate(PatientImpl patient) {
        this.patient = patient;
    }

    /** full constructor */
    public ViralIsolate(PatientImpl patient, String sampleId, Date sampleDate) {
        this.patient = patient;
        this.sampleId = sampleId;
        this.sampleDate = sampleDate;
    }

    // Property accessors
    public Integer getViralIsolateIi() {
        return this.viralIsolateIi;
    }

    public void setViralIsolateIi(Integer viralIsolateIi) {
        this.viralIsolateIi = viralIsolateIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public String getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    public Date getSampleDate() {
        return this.sampleDate;
    }

    public void setSampleDate(Date sampleDate) {
        this.sampleDate = sampleDate;
    }

}
