#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

cd "$1/inputs/"

vd_file="$1/inputs/mut_treated.vd"
idt_file="$1/inputs/mut_treated.idt"
datacount=$(wc -l mut_treated.idt | awk -F " " '{print $1}')
ess=1
stat_file="$1/inputs/mut_treated.stat"
iterations=10000
coolings=10
cost=1.2
prog_file="$1/inputs/progress"
str_file="$1/inputs/mut_treated.str"

echo "Starting bnlearner" >> $monitor_file
bnlearner $vd_file $idt_file $datacount $ess $stat_file $str_file $iterations $coolings $cost $prog_file >> $monitor_file
echo "Bnlearner finished" >> $monitor_file
cp "$1/inputs/mut_treated.str" "$1/outputs/mut_treated.str"
rm "$running_file"
echo "ENDED_SUCCES" > "$1/.ended"
