package net.sf.regadb.db;


/**
 * AttributeGroup generated by hbm2java
 */
public class AttributeGroup implements java.io.Serializable {

    private Integer attributeGroupIi;

    private int version;

    private String groupName;

    public AttributeGroup() {
    }

    public AttributeGroup(String groupName) {
        this.groupName = groupName;
    }

    public Integer getAttributeGroupIi() {
        return this.attributeGroupIi;
    }

    public void setAttributeGroupIi(Integer attributeGroupIi) {
        this.attributeGroupIi = attributeGroupIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
