package net.sf.regadb.db;


/**
 * CombinedQuery generated by hbm2java
 */
public class CombinedQuery implements java.io.Serializable {

    // Fields    

    private Integer combinedQueryIi;

    private String name;

    // Constructors

    /** default constructor */
    public CombinedQuery() {
    }

    /** full constructor */
    public CombinedQuery(String name) {
        this.name = name;
    }

    // Property accessors
    public Integer getCombinedQueryIi() {
        return this.combinedQueryIi;
    }

    public void setCombinedQueryIi(Integer combinedQueryIi) {
        this.combinedQueryIi = combinedQueryIi;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
