package net.sf.regadb.db;


/**
 * CombinedQueryDefinition generated by hbm2java
 */
public class CombinedQueryDefinition implements java.io.Serializable {

    private CombinedQueryDefinitionId id;

    private QueryDefinition queryDefinition;

    private CombinedQuery combinedQuery;

    private int number;

    private String name;

    public CombinedQueryDefinition() {
    }

    public CombinedQueryDefinition(CombinedQueryDefinitionId id,
            QueryDefinition queryDefinition, CombinedQuery combinedQuery,
            int number) {
        this.id = id;
        this.queryDefinition = queryDefinition;
        this.combinedQuery = combinedQuery;
        this.number = number;
    }

    public CombinedQueryDefinition(CombinedQueryDefinitionId id,
            QueryDefinition queryDefinition, CombinedQuery combinedQuery,
            int number, String name) {
        this.id = id;
        this.queryDefinition = queryDefinition;
        this.combinedQuery = combinedQuery;
        this.number = number;
        this.name = name;
    }

    public CombinedQueryDefinitionId getId() {
        return this.id;
    }

    public void setId(CombinedQueryDefinitionId id) {
        this.id = id;
    }

    public QueryDefinition getQueryDefinition() {
        return this.queryDefinition;
    }

    public void setQueryDefinition(QueryDefinition queryDefinition) {
        this.queryDefinition = queryDefinition;
    }

    public CombinedQuery getCombinedQuery() {
        return this.combinedQuery;
    }

    public void setCombinedQuery(CombinedQuery combinedQuery) {
        this.combinedQuery = combinedQuery;
    }

    public int getNumber() {
        return this.number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
