package net.sf.regadb.db;


import java.util.HashSet;
import java.util.Set;

/**
 * Genome generated by hbm2java
 */
public class Genome implements java.io.Serializable {

    // Fields    

    private Integer genomeIi;

    private int version;

    private String organismName;

    private String organismDescription;

    private String genbankNumber;

    private Set<DrugGeneric> drugGenerics = new HashSet<DrugGeneric>(0);

    private Set<OpenReadingFrame> openReadingFrames = new HashSet<OpenReadingFrame>(
            0);

    // Constructors

    /** default constructor */
    public Genome() {
    }

    /** minimal constructor */
    public Genome(String organismName, String organismDescription) {
        this.organismName = organismName;
        this.organismDescription = organismDescription;
    }

    /** full constructor */
    public Genome(String organismName, String organismDescription,
            String genbankNumber, Set<DrugGeneric> drugGenerics,
            Set<OpenReadingFrame> openReadingFrames) {
        this.organismName = organismName;
        this.organismDescription = organismDescription;
        this.genbankNumber = genbankNumber;
        this.drugGenerics = drugGenerics;
        this.openReadingFrames = openReadingFrames;
    }

    // Property accessors
    public Integer getGenomeIi() {
        return this.genomeIi;
    }

    public void setGenomeIi(Integer genomeIi) {
        this.genomeIi = genomeIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getOrganismName() {
        return this.organismName;
    }

    public void setOrganismName(String organismName) {
        this.organismName = organismName;
    }

    public String getOrganismDescription() {
        return this.organismDescription;
    }

    public void setOrganismDescription(String organismDescription) {
        this.organismDescription = organismDescription;
    }

    public String getGenbankNumber() {
        return this.genbankNumber;
    }

    public void setGenbankNumber(String genbankNumber) {
        this.genbankNumber = genbankNumber;
    }

    public Set<DrugGeneric> getDrugGenerics() {
        return this.drugGenerics;
    }

    public void setDrugGenerics(Set<DrugGeneric> drugGenerics) {
        this.drugGenerics = drugGenerics;
    }

    public Set<OpenReadingFrame> getOpenReadingFrames() {
        return this.openReadingFrames;
    }

    public void setOpenReadingFrames(Set<OpenReadingFrame> openReadingFrames) {
        this.openReadingFrames = openReadingFrames;
    }

}
