package net.sf.regadb.db;


import java.util.HashSet;
import java.util.Set;

/**
 * OpenReadingFrame generated by hbm2java
 */
public class OpenReadingFrame implements java.io.Serializable {

    private Integer openReadingFrameIi;

    private int version;

    private Genome genome;

    private String name;

    private String description;

    private String referenceSequence;

    private Set<Protein> proteins = new HashSet<Protein>(0);

    public OpenReadingFrame() {
    }

    public OpenReadingFrame(Genome genome, String name, String description,
            String referenceSequence) {
        this.genome = genome;
        this.name = name;
        this.description = description;
        this.referenceSequence = referenceSequence;
    }

    public OpenReadingFrame(Genome genome, String name, String description,
            String referenceSequence, Set<Protein> proteins) {
        this.genome = genome;
        this.name = name;
        this.description = description;
        this.referenceSequence = referenceSequence;
        this.proteins = proteins;
    }

    public Integer getOpenReadingFrameIi() {
        return this.openReadingFrameIi;
    }

    public void setOpenReadingFrameIi(Integer openReadingFrameIi) {
        this.openReadingFrameIi = openReadingFrameIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Genome getGenome() {
        return this.genome;
    }

    public void setGenome(Genome genome) {
        this.genome = genome;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getReferenceSequence() {
        return this.referenceSequence;
    }

    public void setReferenceSequence(String referenceSequence) {
        this.referenceSequence = referenceSequence;
    }

    public Set<Protein> getProteins() {
        return this.proteins;
    }

    public void setProteins(Set<Protein> proteins) {
        this.proteins = proteins;
    }

}
