package net.sf.regadb.db;


import java.util.Date;

/**
 * PatientEventValue generated by hbm2java
 */
public class PatientEventValue implements java.io.Serializable {

    // Fields    

    private Integer patientEventValueIi;

    private int version;

    private PatientImpl patient;

    private EventNominalValue eventNominalValue;

    private Event event;

    private String value;

    private Date startDate;

    private Date endDate;

    // Constructors

    /** default constructor */
    public PatientEventValue() {
    }

    /** minimal constructor */
    public PatientEventValue(PatientImpl patient, Event event) {
        this.patient = patient;
        this.event = event;
    }

    /** full constructor */
    public PatientEventValue(PatientImpl patient,
            EventNominalValue eventNominalValue, Event event, String value,
            Date startDate, Date endDate) {
        this.patient = patient;
        this.eventNominalValue = eventNominalValue;
        this.event = event;
        this.value = value;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    // Property accessors
    public Integer getPatientEventValueIi() {
        return this.patientEventValueIi;
    }

    public void setPatientEventValueIi(Integer patientEventValueIi) {
        this.patientEventValueIi = patientEventValueIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public EventNominalValue getEventNominalValue() {
        return this.eventNominalValue;
    }

    public void setEventNominalValue(EventNominalValue eventNominalValue) {
        this.eventNominalValue = eventNominalValue;
    }

    public Event getEvent() {
        return this.event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

}
