package net.sf.regadb.db;


/**
 * SplicingPosition generated by hbm2java
 */
public class SplicingPosition implements java.io.Serializable {

    // Fields    

    private Integer splicingPositionIi;

    private int version;

    private Protein protein;

    private int ntPosition;

    // Constructors

    /** default constructor */
    public SplicingPosition() {
    }

    /** full constructor */
    public SplicingPosition(Protein protein, int ntPosition) {
        this.protein = protein;
        this.ntPosition = ntPosition;
    }

    // Property accessors
    public Integer getSplicingPositionIi() {
        return this.splicingPositionIi;
    }

    public void setSplicingPositionIi(Integer splicingPositionIi) {
        this.splicingPositionIi = splicingPositionIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Protein getProtein() {
        return this.protein;
    }

    public void setProtein(Protein protein) {
        this.protein = protein;
    }

    public int getNtPosition() {
        return this.ntPosition;
    }

    public void setNtPosition(int ntPosition) {
        this.ntPosition = ntPosition;
    }

}
