package net.sf.regadb.db;


/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

    private Integer testIi;

    private int version;

    private Analysis analysis;

    private TestType testType;

    private String description;

    public Test() {
    }

    public Test(TestType testType, String description) {
        this.testType = testType;
        this.description = description;
    }

    public Test(Analysis analysis, TestType testType, String description) {
        this.analysis = analysis;
        this.testType = testType;
        this.description = description;
    }

    public Integer getTestIi() {
        return this.testIi;
    }

    public void setTestIi(Integer testIi) {
        this.testIi = testIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Analysis getAnalysis() {
        return this.analysis;
    }

    public void setAnalysis(Analysis analysis) {
        this.analysis = analysis;
    }

    public TestType getTestType() {
        return this.testType;
    }

    public void setTestType(TestType testType) {
        this.testType = testType;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
