package net.sf.regadb.db;


/**
 * TherapyCommercialId generated by hbm2java
 */
public class TherapyCommercialId implements java.io.Serializable {

    private Therapy therapy;

    private DrugCommercial drugCommercial;

    public TherapyCommercialId() {
    }

    public TherapyCommercialId(Therapy therapy, DrugCommercial drugCommercial) {
        this.therapy = therapy;
        this.drugCommercial = drugCommercial;
    }

    public Therapy getTherapy() {
        return this.therapy;
    }

    public void setTherapy(Therapy therapy) {
        this.therapy = therapy;
    }

    public DrugCommercial getDrugCommercial() {
        return this.drugCommercial;
    }

    public void setDrugCommercial(DrugCommercial drugCommercial) {
        this.drugCommercial = drugCommercial;
    }

}
