package net.sf.regadb.db;


/**
 * TherapyGenericId generated by hbm2java
 */
public class TherapyGenericId implements java.io.Serializable {

    private Therapy therapy;

    private DrugGeneric drugGeneric;

    public TherapyGenericId() {
    }

    public TherapyGenericId(Therapy therapy, DrugGeneric drugGeneric) {
        this.therapy = therapy;
        this.drugGeneric = drugGeneric;
    }

    public Therapy getTherapy() {
        return this.therapy;
    }

    public void setTherapy(Therapy therapy) {
        this.therapy = therapy;
    }

    public DrugGeneric getDrugGeneric() {
        return this.drugGeneric;
    }

    public void setDrugGeneric(DrugGeneric drugGeneric) {
        this.drugGeneric = drugGeneric;
    }

}
