#!/bin/bash

monitor_file="$1/.monitor"
running_file="$1/.running"

cp /dev/null $monitor_file

type="$1/inputs/type"
seqs_in="$1/inputs/sequences"
matrix="$1/inputs/matrix"
gapopen="$1/inputs/gapopen"
gapext="$1/inputs/gapext"

seqs_out="$1/outputs/sequences"
score_out="$1/outputs/score"

if [ "$type" = "NT" ]; then
	ls $matrix || matrix=NUC.4.4
	matrix="-pwdnamatrix=$matrix"
else
	ls $matrix || matrix=BLOSUM
	matrix="-pwmatrix=$matrix"
fi

if [ `ls $gapopen` ]; then
	gapopen=`cat $gapopen`
else
	gapopen=-10
fi

if [ `ls $gapext` ]; then
	gapext=`cat $gapext`
else
	gapext=-3.3
fi

command="clustalw -infile=$seqs_in -outfile=$seqs_out -align -output=gde -pwgapopen=$gapopen -pwgapext=$gapext $matrix"
echo $command >> $monitor_file
$command >> $monitor_file 2>> $monitor_file

grep 'Alignment Score' $monitor_file | cut -f 3 -d ' ' > $score_out
sed -i -e 's/#/>/' -e 's/%/>/' $seqs_out

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"

