#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Preparing files..." >> $monitor_file

viral_isolate_file="$1/inputs/viral_isolate"
asi_rules_file="$1/inputs/asi_rules"

interpretation_file="$1/outputs/interpretation"

echo "Starting HIV Drug Resistance Interpretation..." >> $monitor_file

LD_LIBRARY_PATH=/soft/lib:$LD_LIBRARY_PATH /soft/bin/interpretservice $viral_isolate_file $asi_rules_file >> $interpretation_file 2>> $monitor_file 

echo "Calculation ended" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"
