/*
 * SampleJPanel.java
 *
 * Created on November 19, 2003, 11:14 AM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.queryeditor.fastaexport;

import java.io.StringWriter;
import java.io.Writer;

/**
 *
 * @author  kdg
 */
public class PreviewJPanel extends javax.swing.JPanel {
    
    private FastaExporter fastaExporter;
    
    /** Creates new form SampleJPanel */
    public PreviewJPanel(FastaExporter fastaExporter) {
        this.fastaExporter = fastaExporter;
        initComponents();
        recalc();
    }
    
    public void recalc() {
        StringWriter writer = new StringWriter();
        fastaExporter.writeFasta(writer, 8, null);
        sampleJTextArea.setText(writer.toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        sampleJTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Preview"));
        add(sampleJTextArea, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea sampleJTextArea;
    // End of variables declaration//GEN-END:variables
    
}
