/*
 * ThreadPanel.java
 *
 * Created on March 26, 2001, 10:09 AM
 *
 * Copyright 2005 PharmaDM. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of
 * PharmaDM ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with PharmaDM.
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.util.work;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenuItem;
import javax.swing.JProgressBar;
import javax.swing.JToggleButton;


/**
 * A JPanel to show the progress of a thread doing work.
 * @author  kdg
 */
class ThreadPanel extends javax.swing.JPanel {
    /** Creates new form ThreadPanel */
    public ThreadPanel() {
        initComponents();
        this.jButtonStop.setIcon(new ImageIcon(RelativeResourceURLfetcher.fetch(ThreadPanel.class,"Stop16.gif")));
        this.jToggleButtonPauze.setIcon(new ImageIcon(RelativeResourceURLfetcher.fetch(ThreadPanel.class,"Pause16.gif")));
    }
    
    public JToggleButton getToggleButtonPauze() {
        return this.jToggleButtonPauze;
    }
    
    public JButton getButtonAbort() {
        return this.jButtonStop;
    }

    
    public void setDescription(String s) {
        this.progressBar.setString(s);
    }
    
    public JProgressBar getProgressBar() {
        return progressBar;
    }
    
    public void setAbortEnabled(boolean enable) {
        this.jButtonStop.setVisible(enable);
    }
    
    public void setPauseEnabled(boolean enable) {
        this.jToggleButtonPauze.setVisible(enable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressBar = new javax.swing.JProgressBar();
        jButtonStop = new javax.swing.JButton();
        jToggleButtonPauze = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(35, 12));
        setPreferredSize(new java.awt.Dimension(75, 20));
        progressBar.setBorder(null);
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 200));
        progressBar.setMinimumSize(new java.awt.Dimension(10, 16));
        progressBar.setPreferredSize(new java.awt.Dimension(146, 18));
        progressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(progressBar, gridBagConstraints);

        jButtonStop.setFont(new java.awt.Font("Dialog", 0, 10));
        jButtonStop.setToolTipText("Stop this process.");
        jButtonStop.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonStop.setMaximumSize(new java.awt.Dimension(16, 16));
        jButtonStop.setMinimumSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jButtonStop, gridBagConstraints);

        jToggleButtonPauze.setFont(new java.awt.Font("Dialog", 0, 10));
        jToggleButtonPauze.setToolTipText(" Pause this process.");
        jToggleButtonPauze.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButtonPauze.setMaximumSize(new java.awt.Dimension(16, 16));
        jToggleButtonPauze.setMinimumSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jToggleButtonPauze, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    // Check for isPopupTrigger() on both mouse released and mouse pressed for cross-platform safety.        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStop;
    private javax.swing.JToggleButton jToggleButtonPauze;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
    
}
