/*
 * JFrame.java
 *
 * Created on June 5, 2002, 11:26 AM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.util.gui.table;

import javax.swing.table.DefaultTableModel;

import com.pharmadm.util.file.table.*;

/**
 * A test class for TablePrinter
 *
 * @author  michael, kdg
 */
public class TestTablePrinter extends javax.swing.JFrame {
    
    /** Creates new form JFrame */
    public TestTablePrinter() {
        initComponents();
        DefaultTableModel model = ((DefaultTableModel)jTable1.getModel());
        model.setValueAt("ABC", 0, 0);
        model.setValueAt("Qwerty", 1, 0);
        model.setValueAt("Row 0 col 1", 0, 1);
        model.setValueAt("Forte 3.0", 1, 1);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveHTMLButton = new javax.swing.JButton();
        jTable1 = new javax.swing.JTable();

        setTitle("Printing Table Test");
        setName("TestFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        printButton.setMnemonic('p');
        printButton.setText("Print");
        printButton.setToolTipText("this will print the page");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jPanel1.add(printButton);

        saveButton.setMnemonic('c');
        saveButton.setText("Save as CSV");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel1.add(saveButton);

        saveHTMLButton.setMnemonic('h');
        saveHTMLButton.setText("Save as HTML");
        saveHTMLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHTMLButtonActionPerformed(evt);
            }
        });

        jPanel1.add(saveHTMLButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setPreferredSize(new java.awt.Dimension(550, 1660));
        jTable1.setRowHeight(830);
        getContentPane().add(jTable1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void saveHTMLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHTMLButtonActionPerformed
        TableSaverHTML htmlSaver = new TableSaverHTML();
        htmlSaver.setTitle("Test table");
        htmlSaver.save(jTable1.getModel());
    }//GEN-LAST:event_saveHTMLButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        new com.pharmadm.util.file.table.TableSaverCSV().save(jTable1.getModel());
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        TablePrinter.printTable(jTable1);
    }//GEN-LAST:event_printButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    public static void main(String args[]) {
        new TestTablePrinter().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveHTMLButton;
    // End of variables declaration//GEN-END:variables
}
