#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Setting files" >> monitor_file
 
organism_name=`cat "$1/inputs/organism_name"`
nt_sequence_file="$1/inputs/nt_sequence"

mutations_file="$1/outputs/codon_mutations"

echo "Starting calc" >> $monitor_file
/soft/bin/regadb_align /soft/wts/file-providers/regadb-genomes/genomes.xml "$organism_name" "$nt_sequence_file" > "$mutations_file" 2> $monitor_file

echo "Calculation ended" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"

