/*
 * SelectPanel.java
 *
 * Created on September 5, 2003, 1:39 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.reporteditor.gui;

import java.awt.GridBagConstraints;
import java.util.*;
import javax.swing.*;
import com.pharmadm.custom.rega.reporteditor.*;
import com.pharmadm.custom.rega.queryeditor.Selection;
import com.pharmadm.custom.rega.queryeditor.ComposedSelection;
import com.pharmadm.custom.rega.queryeditor.SelectionListChangeListener;

/**
 *
 * @author  kristof
 */
public class DataSelectPanel extends javax.swing.JPanel {
    
    // there is a strong correspondence with com.pharmadm.custom.rega.queryeditor.gui.SelectPanel
    // some day we might make a generalization
    
    private ReportFormatEditor controller;
    private QueryOutputReportSeeder seedController;
    
    /** Creates new form SelectPanel */
    public DataSelectPanel(ReportFormatEditor controller, QueryOutputReportSeeder seedController) {
        this.controller = controller;
        this.seedController = seedController;
        initComponents();
        initSelectListComponents();
    }
    
    public void setSeedController(QueryOutputReportSeeder seedController) {
        this.seedController = seedController;
        initSelectListComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridBagLayout());

    }//GEN-END:initComponents
    
    private void initSelectListComponents() {
        makeSelectListComponents(seedController);
        controller.addSelectionListChangeListener(new SelectionListChangeListener() {
            public void listChanged() {
                // maybe not the most efficient (or elegant) implementation
                reInitSelectListComponents(seedController);
                // both revalidate and repaint are required to properly update the GUI
                revalidate();
                repaint();
            }
        });
        seedController.addSeedsChangeListener(new SeedsChangeListener() {
            public void seedsChanged() {
                reInitSelectListComponents(seedController);
                revalidate();
                repaint();
            }
        });
    }
    
    
    private void reInitSelectListComponents(QueryOutputReportSeeder seedController) {
        this.removeAll();
        makeSelectListComponents(seedController);
    }
    
    private void makeSelectListComponents(QueryOutputReportSeeder seedController) {
        //System.err.println("Making new select panel components");
        Iterator outputs = controller.getReportFormat().getSelectionList().getSelections().iterator();
        while (outputs.hasNext()) {
            Selection selection = (Selection)outputs.next();
            DataOutputVariable ovar = (DataOutputVariable)selection.getObject();
            if (selection instanceof ComposedSelection) {
                java.awt.GridBagConstraints gridBagConstraints = new GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridheight = 10;
                gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                if (selection instanceof POJOListSelection) {
                    this.add(new POJOPropertySelectorPanel((POJOListSelection)selection, seedController), gridBagConstraints);
                } else {
                    this.add(new POJOPropertySelectorPanel((POJOSelection)selection, seedController), gridBagConstraints);
                }
            } else {
                java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
                if (selection instanceof DataOutputListSelection) {
                    this.add(new SimpleDataOutputSelectorPanel((DataOutputListSelection)selection, seedController), gridBagConstraints);
                } else {
                    this.add(new SimpleDataOutputSelectorPanel((DataOutputSelection)selection, seedController), gridBagConstraints);
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
