#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Setting files" >> monitor_file
 
nt_sequences_file="$1/inputs/nt_sequences"
region_file="$1/inputs/region"

aa_sequence_file="$1/outputs/aa_sequences"

echo "Starting calc" >> $monitor_file

cat $nt_sequences_file >> $aa_sequence_file
cat $region_file >> $aa_sequence_file
echo "blabla" >> $aa_sequence_file

echo "Calculation ended" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"
