#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Setting Files" >> monitor_file

nexus="$1/inputs/phylo.nex"

echo "Starting Paup" >> $monitor_file
paup $nexus
echo "Tree Finished" >> $monitor_file
mv $1/inputs/tree.phy $1/outputs/tree.phy

rm "$running_file"
echo "ENDED_SUCCES" > "$1/.ended"
