package net.sf.regadb.db;


/**
 * AttributeNominalValue generated by hbm2java
 */
public class AttributeNominalValue implements java.io.Serializable {

    // Fields    

    private Integer nominalValueIi;

    private int version;

    private Attribute attribute;

    private String value;

    // Constructors

    /** default constructor */
    public AttributeNominalValue() {
    }

    /** full constructor */
    public AttributeNominalValue(Attribute attribute, String value) {
        this.attribute = attribute;
        this.value = value;
    }

    // Property accessors
    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
