package net.sf.regadb.db;


/**
 * PatientAttributeValue generated by hbm2java
 */
public class PatientAttributeValue implements java.io.Serializable {

    // Fields    

    private Integer patientAttributeValueIi;

    private int version;

    private Attribute attribute;

    private PatientImpl patient;

    private AttributeNominalValue attributeNominalValue;

    private String value;

    // Constructors

    /** default constructor */
    public PatientAttributeValue() {
    }

    /** minimal constructor */
    public PatientAttributeValue(Attribute attribute, PatientImpl patient) {
        this.attribute = attribute;
        this.patient = patient;
    }

    /** full constructor */
    public PatientAttributeValue(Attribute attribute, PatientImpl patient,
            AttributeNominalValue attributeNominalValue, String value) {
        this.attribute = attribute;
        this.patient = patient;
        this.attributeNominalValue = attributeNominalValue;
        this.value = value;
    }

    // Property accessors
    public Integer getPatientAttributeValueIi() {
        return this.patientAttributeValueIi;
    }

    public void setPatientAttributeValueIi(Integer patientAttributeValueIi) {
        this.patientAttributeValueIi = patientAttributeValueIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Attribute getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public AttributeNominalValue getAttributeNominalValue() {
        return this.attributeNominalValue;
    }

    public void setAttributeNominalValue(
            AttributeNominalValue attributeNominalValue) {
        this.attributeNominalValue = attributeNominalValue;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
