package net.sf.regadb.db;


/**
 * TherapyGeneric generated by hbm2java
 */
public class TherapyGeneric implements java.io.Serializable {

    // Fields    

    private TherapyGenericId id;

    private int version;

    private Double dayDosageMg;

    private boolean placebo;

    private boolean blind;

    private Long frequency;

    // Constructors

    /** default constructor */
    public TherapyGeneric() {
    }

    /** minimal constructor */
    public TherapyGeneric(TherapyGenericId id, boolean placebo, boolean blind) {
        this.id = id;
        this.placebo = placebo;
        this.blind = blind;
    }

    /** full constructor */
    public TherapyGeneric(TherapyGenericId id, Double dayDosageMg,
            boolean placebo, boolean blind, Long frequency) {
        this.id = id;
        this.dayDosageMg = dayDosageMg;
        this.placebo = placebo;
        this.blind = blind;
        this.frequency = frequency;
    }

    // Property accessors
    public TherapyGenericId getId() {
        return this.id;
    }

    public void setId(TherapyGenericId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Double getDayDosageMg() {
        return this.dayDosageMg;
    }

    public void setDayDosageMg(Double dayDosageMg) {
        this.dayDosageMg = dayDosageMg;
    }

    public boolean isPlacebo() {
        return this.placebo;
    }

    public void setPlacebo(boolean placebo) {
        this.placebo = placebo;
    }

    public boolean isBlind() {
        return this.blind;
    }

    public void setBlind(boolean blind) {
        this.blind = blind;
    }

    public Long getFrequency() {
        return this.frequency;
    }

    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }

}
