#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Preparing files..." >> $monitor_file

nt_sequence_file="$1/inputs/nt_sequence"

type_file="$1/outputs/type"
type_file="$1/outputs/type"

echo "Starting HIV type calculation..." >> $monitor_file

/var/www/localhost/htdocs/genotypetool/batch-type.sh $nt_sequence_file "$1/outputs/" >> $monitor_file 2>> $monitor_file 

python /soft/wts/services/regadb-hiv-type/parse_type.py $1/outputs/result.xml $type_file >> $monitor_file 2>> $monitor_file

echo "Calculation ended" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"
