#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Preparing files..." >> $monitor_file

nt_sequence_file="$1/inputs/nt_sequence"

type_file="$1/outputs/type"
subtype_file="$1/outputs/subtype"

echo "Starting subtype calculation..." >> $monitor_file

/var/www/localhost/htdocs/genotypetool/batch-subtype.sh $nt_sequence_file "$1/outputs/" >> $monitor_file 2>> $monitor_file 

python /soft/wts/services/regadb-hiv-subtype/parse_subtype.py $1/outputs/result.xml $subtype_file >> $monitor_file 2>> $monitor_file

echo "Calculation ended" >> $monitor_file

rm "$running_file"

echo "ENDED_SUCCES" > "$1/.ended"
