/*
 * AtomicWhereClauseSelectorPanel.java
 *
 * Created on September 3, 2003, 2:00 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.queryeditor.gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import com.pharmadm.custom.rega.queryeditor.*;

/**
 *
 * @author  kristof
 */
public class AtomicWhereClauseSelectorPanel extends javax.swing.JPanel {
    
    /** Creates new form AtomicWhereClauseSelectorPanel */
    public AtomicWhereClauseSelectorPanel(JRadioButton radioButton, AtomicWhereClauseEditor editor) {
        this.radioButton = radioButton;
        this.editPanel = new AWCEditorPanel(editor);
        initComponents();
        initMoreComponents();
        addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                AtomicWhereClauseSelectorPanel.this.radioButton.setSelected(true);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridBagLayout());

    }//GEN-END:initComponents
    
    private void initMoreComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.NONE;
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        
        add(radioButton, gridBagConstraints);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.gridx = 1;
        add(editPanel, gridBagConstraints);

        
        gridBagConstraints.gridx = 2;
        gridBagConstraints.weightx = 100;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        JPanel spacerPanel = new JPanel();
//        spacerPanel.setPreferredSize(new java.awt.Dimension(1000,1));
        add(spacerPanel, gridBagConstraints);
        
        editPanel.addFocusListener(new java.awt.event.FocusListener() {
            public void focusGained(java.awt.event.FocusEvent fe) {
                radioButton.setSelected(true);
            }
            public void focusLost(java.awt.event.FocusEvent fe) {
            }
        });
        
    }
    
    public AWCEditorPanel getEditorPanel() {
        return editPanel;
    }
    
    public JRadioButton getRadioButton() {
        return radioButton;
    }
    
    public void freeResources() {
        getEditorPanel().freeResources();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private AWCEditorPanel editPanel;
    private JRadioButton radioButton;
}
