/*
 * DatabaseLoginDialog.java
 *
 * Created on October 15, 2003, 4:36 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.queryeditor.gui;

import java.sql.Connection;

import com.pharmadm.custom.rega.queryeditor.RegaSettings;
import com.pharmadm.util.event.PDMEvent;
import com.pharmadm.util.event.PDMEventListener;
import com.pharmadm.util.gui.RDBMSConnectPanel;
import com.pharmadm.util.settings.*;

/**
 *
 * @author  kdg
 */
public class DatabaseLoginDialog extends javax.swing.JDialog {
    
    private RDBMSConnectPanel rdbmsConnectPanel;
    
    /** Creates new form DatabaseLoginDialog */
    public DatabaseLoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initMoreComponents();
    }
    
    private void initMoreComponents() {
        String dbType = ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("DBType")).stringValue();
        String host = ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Host")).stringValue();
        Integer port = (Integer)((IntegerSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Port")).getValue();
        String database = ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Database")).stringValue();
        
        rdbmsConnectPanel = new RDBMSConnectPanel(dbType, host, port, database, null, null);
        getContentPane().add(rdbmsConnectPanel);
        rdbmsConnectPanel.addStateChangeListener(new PDMEventListener() {
            public void processEvent(PDMEvent evt) {
                dispose();
                ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("DBType")).setValue(rdbmsConnectPanel.getDBType());
                ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Host")).setValue(rdbmsConnectPanel.getHost());
                ((IntegerSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Port")).setValue(rdbmsConnectPanel.getPort());
                ((StringSetting)RegaSettings.getInstance().getLastDBLogin().getChild("Database")).setValue(rdbmsConnectPanel.getDatabase());
                RegaSettings.getInstance().save();
            }
        });
        setTitle("Database login");
    }
    
    public Connection getConnection() {
        return rdbmsConnectPanel.getConnection();
    }
    
    public RDBMSConnectPanel getRDBMSConnectPanel() {
        return rdbmsConnectPanel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-347)/2, 400, 347);
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DatabaseLoginDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
