/*
 * WLOEditorPanel.java
 *
 * Created on September 3, 2003, 2:32 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.queryeditor.gui;

import java.util.*;
import javax.swing.*;
import com.pharmadm.custom.rega.queryeditor.*;

/**
 *
 * @author  kristof
 */
public class WLOEditorPanel extends javax.swing.JPanel {
    
    private List configList;
    protected ConfigurationController controller;

    /** Creates new form WLOEditorPanel */
    public WLOEditorPanel(ConfigurationController controller) {
        this.controller = controller;
        initComponents();
        initMoreComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    
    private void initMoreComponents() {
        setLayout(new java.awt.FlowLayout());
        VisualizationComponentFactory factory = controller.getVisualizationComponentFactory();
        configList = new ArrayList();
        Iterator iter = controller.getVisualizationList().iterator();
        while (iter.hasNext()) {
            ConfigurableWord word = (ConfigurableWord)iter.next();
            WordConfigurer wordConfigurer = factory.createComponent(word);
            configList.add(wordConfigurer); 
            try {
                add((java.awt.Component)wordConfigurer);
            } catch (ClassCastException cce) {
                System.out.println("Warning : Can only add objects of class java.awt.Component to GUI");
            }
        }
    }
        
    /** Applies changes made to all visualisation components in the componentList to the corresponding AWCWords */
    public void applyEditings() {
        Iterator iter = configList.iterator();
        while (iter.hasNext()) {
            WordConfigurer confy = (WordConfigurer)iter.next();
            confy.configureWord();
        }
    }
    
    public ConfigurationController getEditor() {
        return controller;
    }
    
    public void addFocusListener(java.awt.event.FocusListener listener) {
        if (configList == null) {
            // I am very sorry to have to add this, but addFocusListener is apparently called in the behind-the-screens initialization
            // (something to ensure serializability...)
            return;
        }
        Iterator iter = configList.iterator();
        while (iter.hasNext()) {
            java.awt.Component confy = (java.awt.Component)iter.next();
            confy.addFocusListener(listener);
        }
    }
    
    public void freeResources() {
        Iterator iter = configList.iterator();
        while (iter.hasNext()) {
            WordConfigurer confy = (WordConfigurer)iter.next();
            confy.freeResources();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
