package net.sf.regadb.db;

// Generated 17/07/2007 16:16:15 by Hibernate Tools 3.2.0.beta8

/**
 * AaInsertionId generated by hbm2java
 */
public class AaInsertionId implements java.io.Serializable {

    // Fields    

    private short insertionPosition;

    private AaSequence aaSequence;

    private short insertionOrder;

    // Constructors

    /** default constructor */
    public AaInsertionId() {
    }

    /** full constructor */
    public AaInsertionId(short insertionPosition, AaSequence aaSequence,
            short insertionOrder) {
        this.insertionPosition = insertionPosition;
        this.aaSequence = aaSequence;
        this.insertionOrder = insertionOrder;
    }

    // Property accessors
    public short getInsertionPosition() {
        return this.insertionPosition;
    }

    public void setInsertionPosition(short insertionPosition) {
        this.insertionPosition = insertionPosition;
    }

    public AaSequence getAaSequence() {
        return this.aaSequence;
    }

    public void setAaSequence(AaSequence aaSequence) {
        this.aaSequence = aaSequence;
    }

    public short getInsertionOrder() {
        return this.insertionOrder;
    }

    public void setInsertionOrder(short insertionOrder) {
        this.insertionOrder = insertionOrder;
    }

}
