package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * AaInsertion generated by hbm2java
 */
public class AaInsertion implements java.io.Serializable {

    // Fields    

    private AaInsertionId id;

    private int version;

    private String aaInsertion;

    private String ntInsertionCodon;

    // Constructors

    /** default constructor */
    public AaInsertion() {
    }

    /** full constructor */
    public AaInsertion(AaInsertionId id, String aaInsertion,
            String ntInsertionCodon) {
        this.id = id;
        this.aaInsertion = aaInsertion;
        this.ntInsertionCodon = ntInsertionCodon;
    }

    // Property accessors
    public AaInsertionId getId() {
        return this.id;
    }

    public void setId(AaInsertionId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getAaInsertion() {
        return this.aaInsertion;
    }

    public void setAaInsertion(String aaInsertion) {
        this.aaInsertion = aaInsertion;
    }

    public String getNtInsertionCodon() {
        return this.ntInsertionCodon;
    }

    public void setNtInsertionCodon(String ntInsertionCodon) {
        this.ntInsertionCodon = ntInsertionCodon;
    }

}
