package net.sf.regadb.db;

// Generated 17/07/2007 16:16:15 by Hibernate Tools 3.2.0.beta8

/**
 * AaMutationId generated by hbm2java
 */
public class AaMutationId implements java.io.Serializable {

    // Fields    

    private short mutationPosition;

    private AaSequence aaSequence;

    // Constructors

    /** default constructor */
    public AaMutationId() {
    }

    /** full constructor */
    public AaMutationId(short mutationPosition, AaSequence aaSequence) {
        this.mutationPosition = mutationPosition;
        this.aaSequence = aaSequence;
    }

    // Property accessors
    public short getMutationPosition() {
        return this.mutationPosition;
    }

    public void setMutationPosition(short mutationPosition) {
        this.mutationPosition = mutationPosition;
    }

    public AaSequence getAaSequence() {
        return this.aaSequence;
    }

    public void setAaSequence(AaSequence aaSequence) {
        this.aaSequence = aaSequence;
    }

}
