package net.sf.regadb.db;

// Generated Jul 18, 2007 4:05:12 PM by Hibernate Tools 3.2.0.beta8

/**
 * AnalysisData generated by hbm2java
 */
public class AnalysisData implements java.io.Serializable {

    // Fields    

    private Integer analysisDataIi;

    private Analysis analysis;

    private String name;

    private byte[] data;

    private String mimetype;

    // Constructors

    /** default constructor */
    public AnalysisData() {
    }

    /** minimal constructor */
    public AnalysisData(Analysis analysis, String mimetype) {
        this.analysis = analysis;
        this.mimetype = mimetype;
    }

    /** full constructor */
    public AnalysisData(Analysis analysis, String name, byte[] data,
            String mimetype) {
        this.analysis = analysis;
        this.name = name;
        this.data = data;
        this.mimetype = mimetype;
    }

    // Property accessors
    public Integer getAnalysisDataIi() {
        return this.analysisDataIi;
    }

    public void setAnalysisDataIi(Integer analysisDataIi) {
        this.analysisDataIi = analysisDataIi;
    }

    public Analysis getAnalysis() {
        return this.analysis;
    }

    public void setAnalysis(Analysis analysis) {
        this.analysis = analysis;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

}
