package net.sf.regadb.db;

// Generated 11/05/2007 16:06:22 by Hibernate Tools 3.2.0.beta8

/**
 * Analysis generated by hbm2java
 */
public class Analysis implements java.io.Serializable {

    // Fields    

    private Integer analysisIi;

    private AnalysisType analysisType;

    private Integer type;

    private String url;

    // Constructors

    /** default constructor */
    public Analysis() {
    }

    /** minimal constructor */
    public Analysis(AnalysisType analysisType) {
        this.analysisType = analysisType;
    }

    /** full constructor */
    public Analysis(AnalysisType analysisType, Integer type, String url) {
        this.analysisType = analysisType;
        this.type = type;
        this.url = url;
    }

    // Property accessors
    public Integer getAnalysisIi() {
        return this.analysisIi;
    }

    public void setAnalysisIi(Integer analysisIi) {
        this.analysisIi = analysisIi;
    }

    public AnalysisType getAnalysisType() {
        return this.analysisType;
    }

    public void setAnalysisType(AnalysisType analysisType) {
        this.analysisType = analysisType;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
