package net.sf.regadb.db;


/**
 * AnalysisData generated by hbm2java
 */
public class AnalysisData implements java.io.Serializable {

    private Integer analysisDataIi;

    private Analysis analysis;

    private String name;

    private byte[] data;

    private String mimetype;

    public AnalysisData() {
    }

    public AnalysisData(Analysis analysis, String mimetype) {
        this.analysis = analysis;
        this.mimetype = mimetype;
    }

    public AnalysisData(Analysis analysis, String name, byte[] data,
            String mimetype) {
        this.analysis = analysis;
        this.name = name;
        this.data = data;
        this.mimetype = mimetype;
    }

    public Integer getAnalysisDataIi() {
        return this.analysisDataIi;
    }

    public void setAnalysisDataIi(Integer analysisDataIi) {
        this.analysisDataIi = analysisDataIi;
    }

    public Analysis getAnalysis() {
        return this.analysis;
    }

    public void setAnalysis(Analysis analysis) {
        this.analysis = analysis;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

}
