package net.sf.regadb.db;


/**
 * AnalysisType generated by hbm2java
 */
public class AnalysisType implements java.io.Serializable {

    private Integer analysisTypeIi;

    private String type;

    public AnalysisType() {
    }

    public AnalysisType(String type) {
        this.type = type;
    }

    public Integer getAnalysisTypeIi() {
        return this.analysisTypeIi;
    }

    public void setAnalysisTypeIi(Integer analysisTypeIi) {
        this.analysisTypeIi = analysisTypeIi;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
