package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * AttributeGroup generated by hbm2java
 */
public class AttributeGroup implements java.io.Serializable {

    // Fields    

    private Integer attributeGroupIi;

    private int version;

    private String groupName;

    // Constructors

    /** default constructor */
    public AttributeGroup() {
    }

    /** full constructor */
    public AttributeGroup(String groupName) {
        this.groupName = groupName;
    }

    // Property accessors
    public Integer getAttributeGroupIi() {
        return this.attributeGroupIi;
    }

    public void setAttributeGroupIi(Integer attributeGroupIi) {
        this.attributeGroupIi = attributeGroupIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
