package net.sf.regadb.db;


/**
 * CombinedQueryDefinitionId generated by hbm2java
 */
public class CombinedQueryDefinitionId implements java.io.Serializable {

    private int combinedQueryIi;

    private int queryDefinitionIi;

    public CombinedQueryDefinitionId() {
    }

    public CombinedQueryDefinitionId(int combinedQueryIi, int queryDefinitionIi) {
        this.combinedQueryIi = combinedQueryIi;
        this.queryDefinitionIi = queryDefinitionIi;
    }

    public int getCombinedQueryIi() {
        return this.combinedQueryIi;
    }

    public void setCombinedQueryIi(int combinedQueryIi) {
        this.combinedQueryIi = combinedQueryIi;
    }

    public int getQueryDefinitionIi() {
        return this.queryDefinitionIi;
    }

    public void setQueryDefinitionIi(int queryDefinitionIi) {
        this.queryDefinitionIi = queryDefinitionIi;
    }

}
