package net.sf.regadb.db;


/**
 * DatasetAccess generated by hbm2java
 */
public class DatasetAccess implements java.io.Serializable {

    private DatasetAccessId id;

    private int version;

    private int permissions;

    private String provider;

    public DatasetAccess() {
    }

    public DatasetAccess(DatasetAccessId id, int permissions, String provider) {
        this.id = id;
        this.permissions = permissions;
        this.provider = provider;
    }

    public DatasetAccessId getId() {
        return this.id;
    }

    public void setId(DatasetAccessId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getPermissions() {
        return this.permissions;
    }

    public void setPermissions(int permissions) {
        this.permissions = permissions;
    }

    public String getProvider() {
        return this.provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

}
