package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * DatasetAccess generated by hbm2java
 */
public class DatasetAccess implements java.io.Serializable {

    // Fields    

    private DatasetAccessId id;

    private int version;

    private int permissions;

    // Constructors

    /** default constructor */
    public DatasetAccess() {
    }

    /** full constructor */
    public DatasetAccess(DatasetAccessId id, int permissions) {
        this.id = id;
        this.permissions = permissions;
    }

    // Property accessors
    public DatasetAccessId getId() {
        return this.id;
    }

    public void setId(DatasetAccessId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getPermissions() {
        return this.permissions;
    }

    public void setPermissions(int permissions) {
        this.permissions = permissions;
    }

}
