package net.sf.regadb.db;

// Generated Feb 19, 2008 5:32:52 PM by Hibernate Tools 3.2.0.beta8

/**
 * EventNominalValue generated by hbm2java
 */
public class EventNominalValue implements java.io.Serializable {

    // Fields    

    private Integer nominalValueIi;

    private int version;

    private Event event;

    private String value;

    // Constructors

    /** default constructor */
    public EventNominalValue() {
    }

    /** full constructor */
    public EventNominalValue(Event event, String value) {
        this.event = event;
        this.value = value;
    }

    // Property accessors
    public Integer getNominalValueIi() {
        return this.nominalValueIi;
    }

    public void setNominalValueIi(Integer nominalValueIi) {
        this.nominalValueIi = nominalValueIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Event getEvent() {
        return this.event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
