package net.sf.regadb.db;

// Generated Feb 20, 2008 4:18:23 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

    // Fields    

    private Integer eventIi;

    private int version;

    private ValueType valueType;

    private String name;

    private Set<EventNominalValue> eventNominalValues = new HashSet<EventNominalValue>(
            0);

    // Constructors

    /** default constructor */
    public Event() {
    }

    /** minimal constructor */
    public Event(String name) {
        this.name = name;
    }

    /** full constructor */
    public Event(ValueType valueType, String name,
            Set<EventNominalValue> eventNominalValues) {
        this.valueType = valueType;
        this.name = name;
        this.eventNominalValues = eventNominalValues;
    }

    // Property accessors
    public Integer getEventIi() {
        return this.eventIi;
    }

    public void setEventIi(Integer eventIi) {
        this.eventIi = eventIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public ValueType getValueType() {
        return this.valueType;
    }

    public void setValueType(ValueType valueType) {
        this.valueType = valueType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<EventNominalValue> getEventNominalValues() {
        return this.eventNominalValues;
    }

    public void setEventNominalValues(Set<EventNominalValue> eventNominalValues) {
        this.eventNominalValues = eventNominalValues;
    }

}
