package net.sf.regadb.db;

// Generated Feb 19, 2008 5:32:52 PM by Hibernate Tools 3.2.0.beta8

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

    // Fields    

    private Integer eventIi;

    private int version;

    private ValueType valueType;

    private String name;

    // Constructors

    /** default constructor */
    public Event() {
    }

    /** minimal constructor */
    public Event(String name) {
        this.name = name;
    }

    /** full constructor */
    public Event(ValueType valueType, String name) {
        this.valueType = valueType;
        this.name = name;
    }

    // Property accessors
    public Integer getEventIi() {
        return this.eventIi;
    }

    public void setEventIi(Integer eventIi) {
        this.eventIi = eventIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public ValueType getValueType() {
        return this.valueType;
    }

    public void setValueType(ValueType valueType) {
        this.valueType = valueType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
