package net.sf.regadb.db;

// Generated 7/05/2007 10:19:16 by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NtSequence generated by hbm2java
 */
public class NtSequence implements java.io.Serializable {

    // Fields    

    private Integer ntSequenceIi;

    private Integer version;

    private ViralIsolate viralIsolate;

    private String nucleotides;

    private String label;

    private Date sequenceDate;

    private Set<AaSequence> aaSequences = new HashSet<AaSequence>(0);

    private Set<TestResult> testResults = new HashSet<TestResult>(0);

    // Constructors

    /** default constructor */
    public NtSequence() {
    }

    /** minimal constructor */
    public NtSequence(ViralIsolate viralIsolate) {
        this.viralIsolate = viralIsolate;
    }

    /** full constructor */
    public NtSequence(ViralIsolate viralIsolate, String nucleotides,
            String label, Date sequenceDate, Set<AaSequence> aaSequences,
            Set<TestResult> testResults) {
        this.viralIsolate = viralIsolate;
        this.nucleotides = nucleotides;
        this.label = label;
        this.sequenceDate = sequenceDate;
        this.aaSequences = aaSequences;
        this.testResults = testResults;
    }

    // Property accessors
    public Integer getNtSequenceIi() {
        return this.ntSequenceIi;
    }

    public void setNtSequenceIi(Integer ntSequenceIi) {
        this.ntSequenceIi = ntSequenceIi;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public ViralIsolate getViralIsolate() {
        return this.viralIsolate;
    }

    public void setViralIsolate(ViralIsolate viralIsolate) {
        this.viralIsolate = viralIsolate;
    }

    public String getNucleotides() {
        return this.nucleotides;
    }

    public void setNucleotides(String nucleotides) {
        this.nucleotides = nucleotides;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Date getSequenceDate() {
        return this.sequenceDate;
    }

    public void setSequenceDate(Date sequenceDate) {
        this.sequenceDate = sequenceDate;
    }

    public Set<AaSequence> getAaSequences() {
        return this.aaSequences;
    }

    public void setAaSequences(Set<AaSequence> aaSequences) {
        this.aaSequences = aaSequences;
    }

    public Set<TestResult> getTestResults() {
        return this.testResults;
    }

    public void setTestResults(Set<TestResult> testResults) {
        this.testResults = testResults;
    }

}
