package net.sf.regadb.db;

// Generated 16/04/2007 11:23:25 by Hibernate Tools 3.2.0.beta8

/**
 * PatientDatasetId generated by hbm2java
 */
public class PatientDatasetId implements java.io.Serializable {

    // Fields    

    private int datasetIi;

    private int patientIi;

    // Constructors

    /** default constructor */
    public PatientDatasetId() {
    }

    /** full constructor */
    public PatientDatasetId(int datasetIi, int patientIi) {
        this.datasetIi = datasetIi;
        this.patientIi = patientIi;
    }

    // Property accessors
    public int getDatasetIi() {
        return this.datasetIi;
    }

    public void setDatasetIi(int datasetIi) {
        this.datasetIi = datasetIi;
    }

    public int getPatientIi() {
        return this.patientIi;
    }

    public void setPatientIi(int patientIi) {
        this.patientIi = patientIi;
    }

}
