package net.sf.regadb.db;


import java.util.HashSet;
import java.util.Set;

/**
 * PatientImpl generated by hbm2java
 */
class PatientImpl implements java.io.Serializable {

    private Integer patientIi;

    private int version;

    private String patientId;

    private Set<PatientEventValue> patientEventValues = new HashSet<PatientEventValue>(
            0);

    private Set<PatientDataset> patientDatasets = new HashSet<PatientDataset>(0);

    private Set<TestResult> testResults = new HashSet<TestResult>(0);

    private Set<PatientAttributeValue> patientAttributeValues = new HashSet<PatientAttributeValue>(
            0);

    private Set<ViralIsolate> viralIsolates = new HashSet<ViralIsolate>(0);

    private Set<Therapy> therapies = new HashSet<Therapy>(0);

    public PatientImpl() {
    }

    public PatientImpl(String patientId) {
        this.patientId = patientId;
    }

    public PatientImpl(String patientId,
            Set<PatientEventValue> patientEventValues,
            Set<PatientDataset> patientDatasets, Set<TestResult> testResults,
            Set<PatientAttributeValue> patientAttributeValues,
            Set<ViralIsolate> viralIsolates, Set<Therapy> therapies) {
        this.patientId = patientId;
        this.patientEventValues = patientEventValues;
        this.patientDatasets = patientDatasets;
        this.testResults = testResults;
        this.patientAttributeValues = patientAttributeValues;
        this.viralIsolates = viralIsolates;
        this.therapies = therapies;
    }

    public Integer getPatientIi() {
        return this.patientIi;
    }

    public void setPatientIi(Integer patientIi) {
        this.patientIi = patientIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getPatientId() {
        return this.patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public Set<PatientEventValue> getPatientEventValues() {
        return this.patientEventValues;
    }

    public void setPatientEventValues(Set<PatientEventValue> patientEventValues) {
        this.patientEventValues = patientEventValues;
    }

    public Set<PatientDataset> getPatientDatasets() {
        return this.patientDatasets;
    }

    public void setPatientDatasets(Set<PatientDataset> patientDatasets) {
        this.patientDatasets = patientDatasets;
    }

    public Set<TestResult> getTestResults() {
        return this.testResults;
    }

    public void setTestResults(Set<TestResult> testResults) {
        this.testResults = testResults;
    }

    public Set<PatientAttributeValue> getPatientAttributeValues() {
        return this.patientAttributeValues;
    }

    public void setPatientAttributeValues(
            Set<PatientAttributeValue> patientAttributeValues) {
        this.patientAttributeValues = patientAttributeValues;
    }

    public Set<ViralIsolate> getViralIsolates() {
        return this.viralIsolates;
    }

    public void setViralIsolates(Set<ViralIsolate> viralIsolates) {
        this.viralIsolates = viralIsolates;
    }

    public Set<Therapy> getTherapies() {
        return this.therapies;
    }

    public void setTherapies(Set<Therapy> therapies) {
        this.therapies = therapies;
    }

}
