package net.sf.regadb.db;

// Generated Feb 19, 2008 5:32:52 PM by Hibernate Tools 3.2.0.beta8

/**
 * PatientEventValue generated by hbm2java
 */
public class PatientEventValue implements java.io.Serializable {

    // Fields    

    private PatientEventValueId id;

    private int version;

    private PatientImpl patient;

    private EventNominalValue eventNominalValue;

    private Event event;

    private String value;

    // Constructors

    /** default constructor */
    public PatientEventValue() {
    }

    /** minimal constructor */
    public PatientEventValue(PatientEventValueId id, PatientImpl patient,
            Event event) {
        this.id = id;
        this.patient = patient;
        this.event = event;
    }

    /** full constructor */
    public PatientEventValue(PatientEventValueId id, PatientImpl patient,
            EventNominalValue eventNominalValue, Event event, String value) {
        this.id = id;
        this.patient = patient;
        this.eventNominalValue = eventNominalValue;
        this.event = event;
        this.value = value;
    }

    // Property accessors
    public PatientEventValueId getId() {
        return this.id;
    }

    public void setId(PatientEventValueId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public EventNominalValue getEventNominalValue() {
        return this.eventNominalValue;
    }

    public void setEventNominalValue(EventNominalValue eventNominalValue) {
        this.eventNominalValue = eventNominalValue;
    }

    public Event getEvent() {
        return this.event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
