package net.sf.regadb.db;

// Generated Feb 19, 2008 5:32:52 PM by Hibernate Tools 3.2.0.beta8

/**
 * PatientEventValueId generated by hbm2java
 */
public class PatientEventValueId implements java.io.Serializable {

    // Fields    

    private int patientIi;

    private int eventIi;

    // Constructors

    /** default constructor */
    public PatientEventValueId() {
    }

    /** full constructor */
    public PatientEventValueId(int patientIi, int eventIi) {
        this.patientIi = patientIi;
        this.eventIi = eventIi;
    }

    // Property accessors
    public int getPatientIi() {
        return this.patientIi;
    }

    public void setPatientIi(int patientIi) {
        this.patientIi = patientIi;
    }

    public int getEventIi() {
        return this.eventIi;
    }

    public void setEventIi(int eventIi) {
        this.eventIi = eventIi;
    }

}
