package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * PatientDatasetId generated by hbm2java
 */
public class PatientDatasetId implements java.io.Serializable {

    // Fields    

    private Dataset dataset;

    private PatientImpl patient;

    // Constructors

    /** default constructor */
    public PatientDatasetId() {
    }

    /** full constructor */
    public PatientDatasetId(Dataset dataset, PatientImpl patient) {
        this.dataset = dataset;
        this.patient = patient;
    }

    // Property accessors
    public Dataset getDataset() {
        return this.dataset;
    }

    public void setDataset(Dataset dataset) {
        this.dataset = dataset;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

}
