package net.sf.regadb.db;


/**
 * QueryDefinitionParameter generated by hbm2java
 */
public class QueryDefinitionParameter implements java.io.Serializable {

    private Integer queryDefinitionParameterIi;

    private QueryDefinitionParameterType queryDefinitionParameterType;

    private QueryDefinition queryDefinition;

    private String name;

    public QueryDefinitionParameter() {
    }

    public QueryDefinitionParameter(
            QueryDefinitionParameterType queryDefinitionParameterType,
            QueryDefinition queryDefinition, String name) {
        this.queryDefinitionParameterType = queryDefinitionParameterType;
        this.queryDefinition = queryDefinition;
        this.name = name;
    }

    public Integer getQueryDefinitionParameterIi() {
        return this.queryDefinitionParameterIi;
    }

    public void setQueryDefinitionParameterIi(Integer queryDefinitionParameterIi) {
        this.queryDefinitionParameterIi = queryDefinitionParameterIi;
    }

    public QueryDefinitionParameterType getQueryDefinitionParameterType() {
        return this.queryDefinitionParameterType;
    }

    public void setQueryDefinitionParameterType(
            QueryDefinitionParameterType queryDefinitionParameterType) {
        this.queryDefinitionParameterType = queryDefinitionParameterType;
    }

    public QueryDefinition getQueryDefinition() {
        return this.queryDefinition;
    }

    public void setQueryDefinition(QueryDefinition queryDefinition) {
        this.queryDefinition = queryDefinition;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
