package net.sf.regadb.db;

// Generated 29/05/2007 14:55:59 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * QueryDefinitionParameter generated by hbm2java
 */
public class QueryDefinitionParameter implements java.io.Serializable {

    // Fields    

    private Integer queryDefinitionParameterIi;

    private QueryDefinitionParameterType queryDefinitionParameterType;

    private QueryDefinition queryDefinition;

    private String name;

    private Set<QueryDefinitionRunParameter> queryDefinitionRunParameters = new HashSet<QueryDefinitionRunParameter>(
            0);

    // Constructors

    /** default constructor */
    public QueryDefinitionParameter() {
    }

    /** full constructor */
    public QueryDefinitionParameter(
            QueryDefinitionParameterType queryDefinitionParameterType,
            QueryDefinition queryDefinition, String name,
            Set<QueryDefinitionRunParameter> queryDefinitionRunParameters) {
        this.queryDefinitionParameterType = queryDefinitionParameterType;
        this.queryDefinition = queryDefinition;
        this.name = name;
        this.queryDefinitionRunParameters = queryDefinitionRunParameters;
    }

    // Property accessors
    public Integer getQueryDefinitionParameterIi() {
        return this.queryDefinitionParameterIi;
    }

    public void setQueryDefinitionParameterIi(Integer queryDefinitionParameterIi) {
        this.queryDefinitionParameterIi = queryDefinitionParameterIi;
    }

    public QueryDefinitionParameterType getQueryDefinitionParameterType() {
        return this.queryDefinitionParameterType;
    }

    public void setQueryDefinitionParameterType(
            QueryDefinitionParameterType queryDefinitionParameterType) {
        this.queryDefinitionParameterType = queryDefinitionParameterType;
    }

    public QueryDefinition getQueryDefinition() {
        return this.queryDefinition;
    }

    public void setQueryDefinition(QueryDefinition queryDefinition) {
        this.queryDefinition = queryDefinition;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<QueryDefinitionRunParameter> getQueryDefinitionRunParameters() {
        return this.queryDefinitionRunParameters;
    }

    public void setQueryDefinitionRunParameters(
            Set<QueryDefinitionRunParameter> queryDefinitionRunParameters) {
        this.queryDefinitionRunParameters = queryDefinitionRunParameters;
    }

}
