package net.sf.regadb.db;

// Generated 29/05/2007 14:55:59 by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QueryDefinitionRun generated by hbm2java
 */
public class QueryDefinitionRun implements java.io.Serializable {

    // Fields    

    private Integer queryDefinitionRunIi;

    private QueryDefinition queryDefinition;

    private SettingsUser settingsUser;

    private Date startdate;

    private Date enddate;

    private Integer status;

    private byte[] result;

    private Set<QueryDefinitionRunParameter> queryDefinitionRunParameters = new HashSet<QueryDefinitionRunParameter>(
            0);

    // Constructors

    /** default constructor */
    public QueryDefinitionRun() {
    }

    /** full constructor */
    public QueryDefinitionRun(QueryDefinition queryDefinition,
            SettingsUser settingsUser, Date startdate, Date enddate,
            Integer status, byte[] result,
            Set<QueryDefinitionRunParameter> queryDefinitionRunParameters) {
        this.queryDefinition = queryDefinition;
        this.settingsUser = settingsUser;
        this.startdate = startdate;
        this.enddate = enddate;
        this.status = status;
        this.result = result;
        this.queryDefinitionRunParameters = queryDefinitionRunParameters;
    }

    // Property accessors
    public Integer getQueryDefinitionRunIi() {
        return this.queryDefinitionRunIi;
    }

    public void setQueryDefinitionRunIi(Integer queryDefinitionRunIi) {
        this.queryDefinitionRunIi = queryDefinitionRunIi;
    }

    public QueryDefinition getQueryDefinition() {
        return this.queryDefinition;
    }

    public void setQueryDefinition(QueryDefinition queryDefinition) {
        this.queryDefinition = queryDefinition;
    }

    public SettingsUser getSettingsUser() {
        return this.settingsUser;
    }

    public void setSettingsUser(SettingsUser settingsUser) {
        this.settingsUser = settingsUser;
    }

    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public byte[] getResult() {
        return this.result;
    }

    public void setResult(byte[] result) {
        this.result = result;
    }

    public Set<QueryDefinitionRunParameter> getQueryDefinitionRunParameters() {
        return this.queryDefinitionRunParameters;
    }

    public void setQueryDefinitionRunParameters(
            Set<QueryDefinitionRunParameter> queryDefinitionRunParameters) {
        this.queryDefinitionRunParameters = queryDefinitionRunParameters;
    }

}
