package net.sf.regadb.db;


/**
 * QueryDefinitionRunParameter generated by hbm2java
 */
public class QueryDefinitionRunParameter implements java.io.Serializable {

    private Integer queryDefinitionRunParameterIi;

    private QueryDefinitionParameter queryDefinitionParameter;

    private QueryDefinitionRun queryDefinitionRun;

    private String value;

    public QueryDefinitionRunParameter() {
    }

    public QueryDefinitionRunParameter(
            QueryDefinitionParameter queryDefinitionParameter,
            QueryDefinitionRun queryDefinitionRun, String value) {
        this.queryDefinitionParameter = queryDefinitionParameter;
        this.queryDefinitionRun = queryDefinitionRun;
        this.value = value;
    }

    public Integer getQueryDefinitionRunParameterIi() {
        return this.queryDefinitionRunParameterIi;
    }

    public void setQueryDefinitionRunParameterIi(
            Integer queryDefinitionRunParameterIi) {
        this.queryDefinitionRunParameterIi = queryDefinitionRunParameterIi;
    }

    public QueryDefinitionParameter getQueryDefinitionParameter() {
        return this.queryDefinitionParameter;
    }

    public void setQueryDefinitionParameter(
            QueryDefinitionParameter queryDefinitionParameter) {
        this.queryDefinitionParameter = queryDefinitionParameter;
    }

    public QueryDefinitionRun getQueryDefinitionRun() {
        return this.queryDefinitionRun;
    }

    public void setQueryDefinitionRun(QueryDefinitionRun queryDefinitionRun) {
        this.queryDefinitionRun = queryDefinitionRun;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
