package net.sf.regadb.db;

// Generated 24/05/2007 10:45:29 by Hibernate Tools 3.2.0.beta8

/**
 * QueryDefinitionParameterType generated by hbm2java
 */
public class QueryDefinitionParameterType implements java.io.Serializable {

    // Fields    

    private Integer queryDefinitionParameterTypeIi;

    private String name;

    // Constructors

    /** default constructor */
    public QueryDefinitionParameterType() {
    }

    /** full constructor */
    public QueryDefinitionParameterType(String name) {
        this.name = name;
    }

    // Property accessors
    public Integer getQueryDefinitionParameterTypeIi() {
        return this.queryDefinitionParameterTypeIi;
    }

    public void setQueryDefinitionParameterTypeIi(
            Integer queryDefinitionParameterTypeIi) {
        this.queryDefinitionParameterTypeIi = queryDefinitionParameterTypeIi;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
