package net.sf.regadb.db;


import java.util.HashSet;
import java.util.Set;

/**
 * QueryDefinition generated by hbm2java
 */
public class QueryDefinition implements java.io.Serializable {

    // Fields    

    private Integer queryDefinitionIi;

    private SettingsUser settingsUser;

    private String name;

    private String description;

    private String query;

    private int queryTypeIi;

    private Set<QueryDefinitionParameter> queryDefinitionParameters = new HashSet<QueryDefinitionParameter>(
            0);

    private Set<QueryDefinitionRun> queryDefinitionRuns = new HashSet<QueryDefinitionRun>(
            0);

    // Constructors

    /** default constructor */
    public QueryDefinition() {
    }

    /** minimal constructor */
    public QueryDefinition(int queryTypeIi) {
        this.queryTypeIi = queryTypeIi;
    }

    /** full constructor */
    public QueryDefinition(SettingsUser settingsUser, String name,
            String description, String query, int queryTypeIi,
            Set<QueryDefinitionParameter> queryDefinitionParameters,
            Set<QueryDefinitionRun> queryDefinitionRuns) {
        this.settingsUser = settingsUser;
        this.name = name;
        this.description = description;
        this.query = query;
        this.queryTypeIi = queryTypeIi;
        this.queryDefinitionParameters = queryDefinitionParameters;
        this.queryDefinitionRuns = queryDefinitionRuns;
    }

    // Property accessors
    public Integer getQueryDefinitionIi() {
        return this.queryDefinitionIi;
    }

    public void setQueryDefinitionIi(Integer queryDefinitionIi) {
        this.queryDefinitionIi = queryDefinitionIi;
    }

    public SettingsUser getSettingsUser() {
        return this.settingsUser;
    }

    public void setSettingsUser(SettingsUser settingsUser) {
        this.settingsUser = settingsUser;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getQuery() {
        return this.query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    public int getQueryTypeIi() {
        return this.queryTypeIi;
    }

    public void setQueryTypeIi(int queryTypeIi) {
        this.queryTypeIi = queryTypeIi;
    }

    public Set<QueryDefinitionParameter> getQueryDefinitionParameters() {
        return this.queryDefinitionParameters;
    }

    public void setQueryDefinitionParameters(
            Set<QueryDefinitionParameter> queryDefinitionParameters) {
        this.queryDefinitionParameters = queryDefinitionParameters;
    }

    public Set<QueryDefinitionRun> getQueryDefinitionRuns() {
        return this.queryDefinitionRuns;
    }

    public void setQueryDefinitionRuns(
            Set<QueryDefinitionRun> queryDefinitionRuns) {
        this.queryDefinitionRuns = queryDefinitionRuns;
    }

}
