package net.sf.regadb.db;

// Generated 29/05/2007 14:55:59 by Hibernate Tools 3.2.0.beta8

/**
 * QueryDefinitionRunParameter generated by hbm2java
 */
public class QueryDefinitionRunParameter implements java.io.Serializable {

    // Fields    

    private Integer queryDefinitionRunParameterIi;

    private QueryDefinitionParameter queryDefinitionParameter;

    private QueryDefinitionRun queryDefinitionRun;

    private String value;

    // Constructors

    /** default constructor */
    public QueryDefinitionRunParameter() {
    }

    /** full constructor */
    public QueryDefinitionRunParameter(
            QueryDefinitionParameter queryDefinitionParameter,
            QueryDefinitionRun queryDefinitionRun, String value) {
        this.queryDefinitionParameter = queryDefinitionParameter;
        this.queryDefinitionRun = queryDefinitionRun;
        this.value = value;
    }

    // Property accessors
    public Integer getQueryDefinitionRunParameterIi() {
        return this.queryDefinitionRunParameterIi;
    }

    public void setQueryDefinitionRunParameterIi(
            Integer queryDefinitionRunParameterIi) {
        this.queryDefinitionRunParameterIi = queryDefinitionRunParameterIi;
    }

    public QueryDefinitionParameter getQueryDefinitionParameter() {
        return this.queryDefinitionParameter;
    }

    public void setQueryDefinitionParameter(
            QueryDefinitionParameter queryDefinitionParameter) {
        this.queryDefinitionParameter = queryDefinitionParameter;
    }

    public QueryDefinitionRun getQueryDefinitionRun() {
        return this.queryDefinitionRun;
    }

    public void setQueryDefinitionRun(QueryDefinitionRun queryDefinitionRun) {
        this.queryDefinitionRun = queryDefinitionRun;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
