package net.sf.regadb.db;


/**
 * ResistanceInterpretationTemplate generated by hbm2java
 */
public class ResistanceInterpretationTemplate implements java.io.Serializable {

    private Integer templateIi;

    private String name;

    private byte[] document;

    private String filename;

    public ResistanceInterpretationTemplate() {
    }

    public ResistanceInterpretationTemplate(String name, byte[] document,
            String filename) {
        this.name = name;
        this.document = document;
        this.filename = filename;
    }

    public Integer getTemplateIi() {
        return this.templateIi;
    }

    public void setTemplateIi(Integer templateIi) {
        this.templateIi = templateIi;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getDocument() {
        return this.document;
    }

    public void setDocument(byte[] document) {
        this.document = document;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

}
