package net.sf.regadb.db;

// Generated 4/07/2007 17:20:42 by Hibernate Tools 3.2.0.beta8

/**
 * ResistanceInterpretationTemplate generated by hbm2java
 */
public class ResistanceInterpretationTemplate implements java.io.Serializable {

    // Fields    

    private Integer templateIi;

    private String name;

    private byte[] document;

    // Constructors

    /** default constructor */
    public ResistanceInterpretationTemplate() {
    }

    /** full constructor */
    public ResistanceInterpretationTemplate(String name, byte[] document) {
        this.name = name;
        this.document = document;
    }

    // Property accessors
    public Integer getTemplateIi() {
        return this.templateIi;
    }

    public void setTemplateIi(Integer templateIi) {
        this.templateIi = templateIi;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getDocument() {
        return this.document;
    }

    public void setDocument(byte[] document) {
        this.document = document;
    }

}
