package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * TherapyGeneric generated by hbm2java
 */
public class TherapyGeneric implements java.io.Serializable {

    // Fields    

    private TherapyGenericId id;

    private int version;

    private Double dayDosageMg;

    // Constructors

    /** default constructor */
    public TherapyGeneric() {
    }

    /** minimal constructor */
    public TherapyGeneric(TherapyGenericId id) {
        this.id = id;
    }

    /** full constructor */
    public TherapyGeneric(TherapyGenericId id, Double dayDosageMg) {
        this.id = id;
        this.dayDosageMg = dayDosageMg;
    }

    // Property accessors
    public TherapyGenericId getId() {
        return this.id;
    }

    public void setId(TherapyGenericId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Double getDayDosageMg() {
        return this.dayDosageMg;
    }

    public void setDayDosageMg(Double dayDosageMg) {
        this.dayDosageMg = dayDosageMg;
    }

}
