package net.sf.regadb.db;

// Generated Jul 18, 2007 4:05:12 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Therapy generated by hbm2java
 */
public class Therapy implements java.io.Serializable {

    // Fields    

    private Integer therapyIi;

    private int version;

    private PatientImpl patient;

    private Date startDate;

    private Date stopDate;

    private String comment;

    private TherapyMotivation motivation;

    private Set<TherapyCommercial> therapyCommercials = new HashSet<TherapyCommercial>(
            0);

    private Set<TherapyGeneric> therapyGenerics = new HashSet<TherapyGeneric>(0);

    // Constructors

    /** default constructor */
    public Therapy() {
    }

    /** minimal constructor */
    public Therapy(PatientImpl patient, Date startDate) {
        this.patient = patient;
        this.startDate = startDate;
    }

    /** full constructor */
    public Therapy(PatientImpl patient, Date startDate, Date stopDate,
            String comment, TherapyMotivation motivation,
            Set<TherapyCommercial> therapyCommercials,
            Set<TherapyGeneric> therapyGenerics) {
        this.patient = patient;
        this.startDate = startDate;
        this.stopDate = stopDate;
        this.comment = comment;
        this.motivation = motivation;
        this.therapyCommercials = therapyCommercials;
        this.therapyGenerics = therapyGenerics;
    }

    // Property accessors
    public Integer getTherapyIi() {
        return this.therapyIi;
    }

    public void setTherapyIi(Integer therapyIi) {
        this.therapyIi = therapyIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStopDate() {
        return this.stopDate;
    }

    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public TherapyMotivation getMotivation() {
        return this.motivation;
    }

    public void setMotivation(TherapyMotivation motivation) {
        this.motivation = motivation;
    }

    public Set<TherapyCommercial> getTherapyCommercials() {
        return this.therapyCommercials;
    }

    public void setTherapyCommercials(Set<TherapyCommercial> therapyCommercials) {
        this.therapyCommercials = therapyCommercials;
    }

    public Set<TherapyGeneric> getTherapyGenerics() {
        return this.therapyGenerics;
    }

    public void setTherapyGenerics(Set<TherapyGeneric> therapyGenerics) {
        this.therapyGenerics = therapyGenerics;
    }

}
