package net.sf.regadb.db;


/**
 * TherapyCommercial generated by hbm2java
 */
public class TherapyCommercial implements java.io.Serializable {

    private TherapyCommercialId id;

    private int version;

    private Double dayDosageUnits;

    private boolean placebo;

    private boolean blind;

    private Long frequency;

    public TherapyCommercial() {
    }

    public TherapyCommercial(TherapyCommercialId id, boolean placebo,
            boolean blind) {
        this.id = id;
        this.placebo = placebo;
        this.blind = blind;
    }

    public TherapyCommercial(TherapyCommercialId id, Double dayDosageUnits,
            boolean placebo, boolean blind, Long frequency) {
        this.id = id;
        this.dayDosageUnits = dayDosageUnits;
        this.placebo = placebo;
        this.blind = blind;
        this.frequency = frequency;
    }

    public TherapyCommercialId getId() {
        return this.id;
    }

    public void setId(TherapyCommercialId id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Double getDayDosageUnits() {
        return this.dayDosageUnits;
    }

    public void setDayDosageUnits(Double dayDosageUnits) {
        this.dayDosageUnits = dayDosageUnits;
    }

    public boolean isPlacebo() {
        return this.placebo;
    }

    public void setPlacebo(boolean placebo) {
        this.placebo = placebo;
    }

    public boolean isBlind() {
        return this.blind;
    }

    public void setBlind(boolean blind) {
        this.blind = blind;
    }

    public Long getFrequency() {
        return this.frequency;
    }

    public void setFrequency(Long frequency) {
        this.frequency = frequency;
    }

}
