package net.sf.regadb.db;

// Generated 18/05/2007 15:38:06 by Hibernate Tools 3.2.0.beta8

/**
 * TherapyDrugsId generated by hbm2java
 */
public class TherapyDrugsId implements java.io.Serializable {

    // Fields    

    private int therapyIi;

    private String drugs;

    // Constructors

    /** default constructor */
    public TherapyDrugsId() {
    }

    /** full constructor */
    public TherapyDrugsId(int therapyIi, String drugs) {
        this.therapyIi = therapyIi;
        this.drugs = drugs;
    }

    // Property accessors
    public int getTherapyIi() {
        return this.therapyIi;
    }

    public void setTherapyIi(int therapyIi) {
        this.therapyIi = therapyIi;
    }

    public String getDrugs() {
        return this.drugs;
    }

    public void setDrugs(String drugs) {
        this.drugs = drugs;
    }

}
