package net.sf.regadb.db;

// Generated Jul 18, 2007 4:05:12 PM by Hibernate Tools 3.2.0.beta8

/**
 * TherapyCommercialId generated by hbm2java
 */
public class TherapyCommercialId implements java.io.Serializable {

    // Fields    

    private Therapy therapy;

    private DrugCommercial drugCommercial;

    // Constructors

    /** default constructor */
    public TherapyCommercialId() {
    }

    /** full constructor */
    public TherapyCommercialId(Therapy therapy, DrugCommercial drugCommercial) {
        this.therapy = therapy;
        this.drugCommercial = drugCommercial;
    }

    // Property accessors
    public Therapy getTherapy() {
        return this.therapy;
    }

    public void setTherapy(Therapy therapy) {
        this.therapy = therapy;
    }

    public DrugCommercial getDrugCommercial() {
        return this.drugCommercial;
    }

    public void setDrugCommercial(DrugCommercial drugCommercial) {
        this.drugCommercial = drugCommercial;
    }

}
