package net.sf.regadb.db;

// Generated Jul 18, 2007 4:05:12 PM by Hibernate Tools 3.2.0.beta8

/**
 * TherapyMotivation generated by hbm2java
 */
public class TherapyMotivation implements java.io.Serializable {

    // Fields    

    private Integer therapyMotivationIi;

    private int version;

    private String value;

    // Constructors

    /** default constructor */
    public TherapyMotivation() {
    }

    /** full constructor */
    public TherapyMotivation(String value) {
        this.value = value;
    }

    // Property accessors
    public Integer getTherapyMotivationIi() {
        return this.therapyMotivationIi;
    }

    public void setTherapyMotivationIi(Integer therapyMotivationIi) {
        this.therapyMotivationIi = therapyMotivationIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
