package net.sf.regadb.db;

// Generated Jul 18, 2007 4:05:12 PM by Hibernate Tools 3.2.0.beta8

/**
 * ValueType generated by hbm2java
 */
public class ValueType implements java.io.Serializable {

    // Fields    

    private Integer valueTypeIi;

    private int version;

    private String description;

    private Double minimum;

    private Double maximum;

    private Boolean multiple;

    // Constructors

    /** default constructor */
    public ValueType() {
    }

    /** minimal constructor */
    public ValueType(String description) {
        this.description = description;
    }

    /** full constructor */
    public ValueType(String description, Double minimum, Double maximum,
            Boolean multiple) {
        this.description = description;
        this.minimum = minimum;
        this.maximum = maximum;
        this.multiple = multiple;
    }

    // Property accessors
    public Integer getValueTypeIi() {
        return this.valueTypeIi;
    }

    public void setValueTypeIi(Integer valueTypeIi) {
        this.valueTypeIi = valueTypeIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getMinimum() {
        return this.minimum;
    }

    public void setMinimum(Double minimum) {
        this.minimum = minimum;
    }

    public Double getMaximum() {
        return this.maximum;
    }

    public void setMaximum(Double maximum) {
        this.maximum = maximum;
    }

    public Boolean getMultiple() {
        return this.multiple;
    }

    public void setMultiple(Boolean multiple) {
        this.multiple = multiple;
    }

}
