package net.sf.regadb.db;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ViralIsolate generated by hbm2java
 */
public class ViralIsolate implements java.io.Serializable {

    private Integer viralIsolateIi;

    private int version;

    private PatientImpl patient;

    private String sampleId;

    private Date sampleDate;
    
    private Genome genome;

    private Set<NtSequence> ntSequences = new HashSet<NtSequence>(0);

    private Set<TestResult> testResults = new HashSet<TestResult>(0);

    public ViralIsolate() {
    }

    public ViralIsolate(PatientImpl patient) {
        this.patient = patient;
    }

    public ViralIsolate(PatientImpl patient, String sampleId, Date sampleDate,
    		Genome genome,
            Set<NtSequence> ntSequences, Set<TestResult> testResults) {
        this.patient = patient;
        this.sampleId = sampleId;
        this.sampleDate = sampleDate;
        this.ntSequences = ntSequences;
        this.testResults = testResults;
        this.genome = genome;
    }

	public Integer getViralIsolateIi() {
        return this.viralIsolateIi;
    }

    public void setViralIsolateIi(Integer viralIsolateIi) {
        this.viralIsolateIi = viralIsolateIi;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public PatientImpl getPatient() {
        return this.patient;
    }

    public void setPatient(PatientImpl patient) {
        this.patient = patient;
    }

    public String getSampleId() {
        return this.sampleId;
    }

    public void setSampleId(String sampleId) {
        this.sampleId = sampleId;
    }

    public Date getSampleDate() {
        return this.sampleDate;
    }

    public void setSampleDate(Date sampleDate) {
        this.sampleDate = sampleDate;
    }
    
    public Genome getGenome() {
		return genome;
	}

	public void setGenome(Genome genome) {
		this.genome = genome;
	}

    public Set<NtSequence> getNtSequences() {
        return this.ntSequences;
    }

    public void setNtSequences(Set<NtSequence> ntSequences) {
        this.ntSequences = ntSequences;
    }

    public Set<TestResult> getTestResults() {
        return this.testResults;
    }

    public void setTestResults(Set<TestResult> testResults) {
        this.testResults = testResults;
    }

}
