#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Setting Files" >> monitor_file
script="$1/inputs/Hivgensim.java"
build="path/to/build/file" #TODO

echo "Compiling script" >> monitor_file
ant compile -f $build
echo "Running script" >> monitor_file
ant run -f $build
echo "Script finished" >> monitor_file
echo "Tarring results" >> monitor_file
tar -cvf $1/outputs/result.tar $1/inputs/*
rm "$running_file"
echo "ENDED_SUCCES" > "$1/.ended"