/*
 * ThreadPanel.java
 *
 * Created on March 26, 2001, 10:09 AM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.util.thread;

import javax.swing.*;
import java.awt.event.InputEvent;

/**
 * A JPanel to show the progress of a thread doing work.
 * @author  kdg
 */
public class ThreadPanel extends javax.swing.JPanel {
    /** Creates new form ThreadPanel */
    public ThreadPanel() {
        initComponents();
    }

    public boolean getPauze(){
        return this.jCheckBoxMenuItemPauze.isSelected();
    }
    
    public JCheckBoxMenuItem getCheckBoxPauze() {
        return this.jCheckBoxMenuItemPauze;
    }
        
    public JMenuItem getMenuItemAbort() {
        return this.jMenuItemAbort;
    }

    public void setDescription(String s) {
        this.progressBar.setString(s);
    }
    
    public JProgressBar getProgressBar() {
        return progressBar;
    }
    
    public void setProgressBar(JProgressBar bar) {
        this.remove(progressBar);
        progressBar = bar;
        this.add(progressBar, 1);
    }
    
    public void setAbortEnabled(boolean enable) {
        this.jMenuItemAbort.setEnabled(enable);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPopupMenu = new javax.swing.JPopupMenu();
        jCheckBoxMenuItemPauze = new javax.swing.JCheckBoxMenuItem();
        jMenuItemAbort = new javax.swing.JMenuItem();
        progressBar = new javax.swing.JProgressBar();

        jCheckBoxMenuItemPauze.setText("Pauze");
        jPopupMenu.add(jCheckBoxMenuItemPauze);
        jMenuItemAbort.setText("Abort");
        jPopupMenu.add(jMenuItemAbort);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(35, 12));
        setPreferredSize(new java.awt.Dimension(75, 20));
        progressBar.setBorder(null);
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 200));
        progressBar.setMinimumSize(new java.awt.Dimension(10, 16));
        progressBar.setPreferredSize(new java.awt.Dimension(146, 18));
        progressBar.setStringPainted(true);
        progressBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                progressBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                progressBarMouseReleased(evt);
            }
        });

        add(progressBar);

    }//GEN-END:initComponents

    // Check for isPopupTrigger() on both mouse released and mouse pressed for cross-platform safety.
    private void progressBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressBarMouseReleased
        maybeShowPopup(evt);
    }//GEN-LAST:event_progressBarMouseReleased
        
    private void progressBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressBarMousePressed
        maybeShowPopup(evt);
    }//GEN-LAST:event_progressBarMousePressed
        
    private void maybeShowPopup(java.awt.event.MouseEvent e) {
        if (e.isPopupTrigger()) {
            this.jPopupMenu.show(e.getComponent(),
            e.getX(), e.getY()-this.jPopupMenu.getHeight());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItemAbort;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemPauze;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables
    
}
