/*
 * AtomicClauseSelectionDialog.java
 *
 * Created on September 2, 2003, 7:16 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.gui;

import java.awt.Dimension;
import java.util.*;
import javax.swing.*;

import com.pharmadm.custom.rega.queryeditor.AtomicWhereClause;
import com.pharmadm.custom.rega.queryeditor.QueryContext;

/**
 *
 * @author  kristof
 */
public class AtomicClauseSelectionDialog extends JDialog {
    
	
    /** Creates new form AtomicClauseSelectionDialog */
    public AtomicClauseSelectionDialog(java.awt.Frame parent, QueryContext context, Collection<AtomicWhereClause> clauseList, boolean modal) {
        super(parent, modal);
    	selectorPanel = new CollapsablePanelAWCSelectorPanel(context);
        initComponents();
        initListComponents(clauseList);
        getRootPane().setDefaultButton(okButton);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("Select Query Component to Add");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(selectorPanel, java.awt.BorderLayout.NORTH);
        setPreferredSize(new Dimension(640,560));
        pack();
    }//GEN-END:initComponents
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        freeResources();
    }//GEN-LAST:event_formWindowClosed
    
    private void initListComponents(Collection<AtomicWhereClause> clauseList) {
        for (AtomicWhereClause clause : clauseList) {
        	selectorPanel.addAtomicWhereClause(clause);
        }
        
    	List<JRadioButton> buttons = selectorPanel.getRadioButtons();
    	for (JRadioButton button : buttons) {
    		buttonGroup1.add(button);
    	}
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelSelection();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        applySelection();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public AtomicWhereClause getSelectedClause() {
        return selectedClause;
    }
    
    private void applySelection() {
        selectedClause = null;
        if (selectorPanel.isSelected()) {
			AWCEditorPanel editPanel = selectorPanel.getSelectedClause();
			editPanel.applyEditings();
			selectedClause = editPanel.getClause();
        	
        }
    }
    
    private void freeResources() {
    	selectorPanel.freeResources();
    }
    
    private void cancelSelection() {
    	selectorPanel.freeResources();
        selectedClause = null;
    }
    
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;

    private AtomicWhereClause selectedClause = null;
    private AWCSelectorPanel selectorPanel;
}
