/*
 * SQLViewer.java
 *
 * Created on October 24, 2003, 2:50 PM
 */

/*
 * (C) Copyright 2000-2007 PharmaDM n.v. All rights reserved.
 * 
 * This file is licensed under the terms of the GNU General Public License (GPL) version 2.
 * See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */
package com.pharmadm.custom.rega.gui;

import java.awt.FlowLayout;
import java.awt.GridBagConstraints;

import javax.swing.JButton;

/**
 *
 * @author  kdg
 */
public class SQLViewer extends javax.swing.JDialog {
    
    /** Creates new form SQLViewer */
    public SQLViewer(java.awt.Frame parent, boolean modal, String sqlQuery) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        sqlTextArea.setText(sqlQuery);
    }
    
    public String getQuery() {
    	return sqlTextArea.getText();
    }
    
    public void setEditable(boolean editable) {
    	sqlTextArea.setEditable(editable);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sqlTextArea = new javax.swing.JTextArea();

        setTitle("SQL query");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        FlowLayout flow = new FlowLayout();
        flow.setAlignment(FlowLayout.RIGHT);
        jPanel1.setLayout(flow);

        closeButton.setMnemonic('c');
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        addButton(closeButton);
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        setEditable(false);
        sqlTextArea.setLineWrap(true);
        sqlTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(sqlTextArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }//GEN-END:initComponents
    
    public void addButton(JButton button) {
        jPanel1.add(button);
    }
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String sql = "SELECT *\nFROM DUMMYTABLE dummytable\nWHERE dummytable.dummy_field = 5";
        new SQLViewer(new javax.swing.JFrame(), true, sql).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea sqlTextArea;
    // End of variables declaration//GEN-END:variables
    
}
