#!/bin/sh

monitor_file="$1/.monitor"
running_file="$1/.running"

echo "Setting Files" >> monitor_file
 
reference="$1/inputs/reference.fasta"
sequences="$1/inputs/sequences.fasta"
aligned_sequences="$1/outputs/aligned.sequences.fasta"

echo "Starting Alignment" >> $monitor_file
/home/gbehey0/sequencetool/local_build/src/lib/align $reference $sequences $aligned_sequences
echo "Alignment Done" >> $monitor_file

rm "$running_file"
echo "ENDED_SUCCES" > "$1/.ended"
