create sequence aa_sequence_aa_sequence_ii_seq start with 1;
create table dual_analysis_analysis_ii_seq (zero integer);
insert into dual_analysis_analysis_ii_seq values (0);
create sequence analysis_analysis_ii_seq start with 1;
create table dual_analysis_data_analysis_data_ii_seq (zero integer);
insert into dual_analysis_data_analysis_data_ii_seq values (0);
create sequence analysis_data_analysis_data_ii_seq start with 1;
create table dual_analysis_type_analysis_type_ii_seq (zero integer);
insert into dual_analysis_type_analysis_type_ii_seq values (0);
create sequence analysis_type_analysis_type_ii_seq start with 1;
create table dual_attribute_attribute_ii_seq (zero integer);
insert into dual_attribute_attribute_ii_seq values (0);
create sequence attribute_attribute_ii_seq start with 1;
create table dual_attribute_group_attribute_group_ii_seq (zero integer);
insert into dual_attribute_group_attribute_group_ii_seq values (0);
create sequence attribute_group_attribute_group_ii_seq start with 1;
create table dual_attribute_nominal_value_attribute_nominal_value_ii_seq (zero integer);
insert into dual_attribute_nominal_value_attribute_nominal_value_ii_seq values (0);
create sequence attribute_nominal_value_attribute_nominal_value_ii_seq start with 1;
create table dual_dataset_dataset_ii_seq (zero integer);
insert into dual_dataset_dataset_ii_seq values (0);
create sequence dataset_dataset_ii_seq start with 1;
create table dual_drug_class_drug_class_ii_seq (zero integer);
insert into dual_drug_class_drug_class_ii_seq values (0);
create sequence drug_class_drug_class_ii_seq start with 1;
create table dual_drug_commercial_drug_commercial_ii_seq (zero integer);
insert into dual_drug_commercial_drug_commercial_ii_seq values (0);
create sequence drug_commercial_drug_commercial_ii_seq start with 1;
create table dual_drug_generic_drug_generic_ii_seq (zero integer);
insert into dual_drug_generic_drug_generic_ii_seq values (0);
create sequence drug_generic_drug_generic_ii_seq start with 1;
create table dual_nt_sequence_nt_sequence_ii_seq (zero integer);
insert into dual_nt_sequence_nt_sequence_ii_seq values (0);
create sequence nt_sequence_nt_sequence_ii_seq start with 1;
create table dual_patient_patient_ii_seq (zero integer);
insert into dual_patient_patient_ii_seq values (0);
create sequence patient_patient_ii_seq start with 1;
create table dual_protein_protein_ii_seq (zero integer);
insert into dual_protein_protein_ii_seq values (0);
create sequence protein_protein_ii_seq start with 1;
create table dual_query_definition_parameter_query_definition_parameter_ii_seq (zero integer);
insert into dual_query_definition_parameter_query_definition_parameter_ii_seq values (0);
create sequence query_definition_parameter_query_definition_parameter_ii_seq start with 1;
create table dual_query_definition_parameter_type_query_definition_parameter_type_ii_seq (zero integer);
insert into dual_query_definition_parameter_type_query_definition_parameter_type_ii_seq values (0);
create sequence query_definition_parameter_type_query_definition_parameter_type_ii_seq start with 1;
create table dual_query_definition_query_definition_ii_seq (zero integer);
insert into dual_query_definition_query_definition_ii_seq values (0);
create sequence query_definition_query_definition_ii_seq start with 1;
create table dual_query_definition_run_parameter_query_definition_run_parameter_ii_seq (zero integer);
insert into dual_query_definition_run_parameter_query_definition_run_parameter_ii_seq values (0);
create sequence query_definition_run_parameter_query_definition_run_parameter_ii_seq start with 1;
create table dual_query_definition_run_query_definition_run_ii_seq (zero integer);
insert into dual_query_definition_run_query_definition_run_ii_seq values (0);
create sequence query_definition_run_query_definition_run_ii_seq start with 1;
create table dual_resistance_interpretation_template_resistance_interpretation_template_ii_seq (zero integer);
insert into dual_resistance_interpretation_template_resistance_interpretation_template_ii_seq values (0);
create sequence resistance_interpretation_template_resistance_interpretation_template_ii_seq start with 1;
create table dual_test_nominal_value_test_nominal_value_ii_seq (zero integer);
insert into dual_test_nominal_value_test_nominal_value_ii_seq values (0);
create sequence test_nominal_value_test_nominal_value_ii_seq start with 1;
create table dual_test_object_test_object_ii_seq (zero integer);
insert into dual_test_object_test_object_ii_seq values (0);
create sequence test_object_test_object_ii_seq start with 1;
create table dual_test_result_test_result_ii_seq (zero integer);
insert into dual_test_result_test_result_ii_seq values (0);
create sequence test_result_test_result_ii_seq start with 1;
create table dual_test_test_ii_seq (zero integer);
insert into dual_test_test_ii_seq values (0);
create sequence test_test_ii_seq start with 1;
create table dual_test_type_test_type_ii_seq (zero integer);
insert into dual_test_type_test_type_ii_seq values (0);
create sequence test_type_test_type_ii_seq start with 1;
create table dual_therapy_motivation_therapy_motivation_ii_seq (zero integer);
insert into dual_therapy_motivation_therapy_motivation_ii_seq values (0);
create sequence therapy_motivation_therapy_motivation_ii_seq start with 1;
create table dual_therapy_therapy_ii_seq (zero integer);
insert into dual_therapy_therapy_ii_seq values (0);
create sequence therapy_therapy_ii_seq start with 1;
create table dual_user_attribute_user_attribute_ii_seq (zero integer);
insert into dual_user_attribute_user_attribute_ii_seq values (0);
create sequence user_attribute_user_attribute_ii_seq start with 1;
create table dual_value_type_value_type_ii_seq (zero integer);
insert into dual_value_type_value_type_ii_seq values (0);
create sequence value_type_value_type_ii_seq start with 1;
create table dual_viral_isolate_viral_isolate_ii_seq (zero integer);
insert into dual_viral_isolate_viral_isolate_ii_seq values (0);
create sequence viral_isolate_viral_isolate_ii_seq start with 1;
create table commercial_generic (generic_ii integer not null, commercial_ii integer not null, primary key (commercial_ii, generic_ii));
create table public.aa_insertion (insertion_position smallint not null, aa_sequence_ii integer not null, insertion_order smallint not null, version integer not null, aa_insertion varchar(30) not null, nt_insertion_codon varchar(3) not null, primary key (insertion_position, aa_sequence_ii, insertion_order));
create table public.aa_mutation (mutation_position smallint not null, aa_sequence_ii integer not null, version integer not null, aa_reference varchar(1) not null, aa_mutation varchar(30), nt_reference_codon varchar(3) not null, nt_mutation_codon varchar(3), primary key (mutation_position, aa_sequence_ii));
create table public.aa_sequence (aa_sequence_ii integer not null, version integer not null, nt_sequence_ii integer not null, protein_ii integer not null, first_aa_pos smallint not null, last_aa_pos smallint not null, primary key (aa_sequence_ii));
create table public.analysis (analysis_ii integer not null, analysis_type_ii integer not null, url varchar(100), account varchar(50), password varchar(100), baseinputfile varchar(50), baseoutputfile varchar(50), service_name varchar(100), primary key (analysis_ii));
create table public.analysis_data (analysis_data_ii integer not null, analysis_ii integer not null, name varchar(50), data varbinary(255), mimetype varchar(50) not null, primary key (analysis_data_ii));
create table public.analysis_type (analysis_type_ii integer not null, type varchar(50), primary key (analysis_type_ii));
create table public.attribute (attribute_ii integer not null, version integer not null, value_type_ii integer, attribute_group_ii integer, name varchar(50) not null, primary key (attribute_ii));
create table public.attribute_group (attribute_group_ii integer not null, version integer not null, group_name varchar(50), primary key (attribute_group_ii));
create table public.attribute_nominal_value (nominal_value_ii integer not null, version integer not null, attribute_ii integer not null, value varchar(100) not null, primary key (nominal_value_ii));
create table public.dataset (dataset_ii integer not null, version integer not null, uid varchar(50) not null, description varchar(50) not null, creation_date date not null, closed_date date, revision integer, primary key (dataset_ii));
create table public.dataset_access (uid varchar(50) not null, dataset_ii integer not null, version integer not null, permissions integer not null, provider varchar(50) not null, primary key (uid, dataset_ii));
create table public.drug_class (drug_class_ii integer not null, version integer not null, class_id varchar(10) not null, class_name varchar(100) not null, resistance_table_order integer, primary key (drug_class_ii));
create table public.drug_commercial (commercial_ii integer not null, version integer not null, name varchar(100) not null, atc_code varchar(50), primary key (commercial_ii));
create table public.drug_generic (generic_ii integer not null, version integer not null, drug_class_ii integer not null, generic_id varchar(10) not null, generic_name varchar(50) not null, resistance_table_order integer, atc_code varchar(50), primary key (generic_ii));
create table public.nt_sequence (nt_sequence_ii integer not null, version integer not null, viral_isolate_ii integer not null, label varchar(50), sequence_date date, nucleotides longvarchar, primary key (nt_sequence_ii));
create table public.patient (patient_ii integer not null, version integer not null, patient_id varchar(50) not null, last_name varchar(50), first_name varchar(50), birth_date date, death_date date, primary key (patient_ii));
create table public.patient_attribute_value (patient_ii integer not null, attribute_ii integer not null, version integer not null, nominal_value_ii integer, value varchar(100), primary key (patient_ii, attribute_ii));
create table public.patient_dataset (dataset_ii integer not null, patient_ii integer not null, primary key (dataset_ii, patient_ii));
create table public.protein (protein_ii integer not null, version integer not null, abbreviation varchar(50) not null, full_name varchar(50), primary key (protein_ii));
create table public.query_definition (query_definition_ii integer not null, uid varchar(50), name varchar(50), description longvarchar, query longvarchar, primary key (query_definition_ii));
create table public.query_definition_parameter (query_definition_parameter_ii integer not null, query_definition_parameter_type_ii integer, query_definition_ii integer, name varchar(50), primary key (query_definition_parameter_ii));
create table public.query_definition_parameter_type (query_definition_parameter_type_ii integer not null, name varchar(100) not null, id integer not null, primary key (query_definition_parameter_type_ii), unique (name), unique (id));
create table public.query_definition_run (query_definition_run_ii integer not null, query_definition_ii integer, uid varchar(50), startdate date, enddate date, status integer, name varchar(100) not null, result varchar(100), primary key (query_definition_run_ii));
create table public.query_definition_run_parameter (query_definition_run_parameter_ii integer not null, query_definition_parameter_ii integer, query_definition_run_ii integer, value varchar(50), primary key (query_definition_run_parameter_ii));
create table public.resistance_interpretation_template (template_ii integer not null, name varchar(100), document varbinary(255), filename varchar(100), primary key (template_ii));
create table public.settings_user (uid varchar(50) not null, version integer not null, test_ii integer, dataset_ii integer, chart_width integer not null, chart_height integer not null, password varchar(50), email varchar(100), first_name varchar(50), last_name varchar(50), admin bit, enabled bit, primary key (uid));
create table public.test (test_ii integer not null, version integer not null, analysis_ii integer, test_type_ii integer not null, description varchar(50) not null, primary key (test_ii), unique (analysis_ii));
create table public.test_nominal_value (nominal_value_ii integer not null, version integer not null, test_type_ii integer not null, value varchar(100) not null, primary key (nominal_value_ii));
create table public.test_object (test_object_ii integer not null, version integer not null, description varchar(50) not null, test_object_id integer, primary key (test_object_ii));
create table public.test_result (test_result_ii integer not null, version integer not null, test_ii integer not null, generic_ii integer, viral_isolate_ii integer, nominal_value_ii integer, patient_ii integer, nt_sequence_ii integer, value varchar(50), test_date date, sample_id varchar(50), data varbinary(255), primary key (test_result_ii));
create table public.test_type (test_type_ii integer not null, version integer not null, value_type_ii integer, test_object_ii integer not null, description varchar(50) not null, primary key (test_type_ii));
create table public.therapy (therapy_ii integer not null, version integer not null, patient_ii integer not null, start_date date not null, stop_date date, comment varchar(50), therapy_motivation_ii integer, primary key (therapy_ii));
create table public.therapy_commercial (therapy_ii integer not null, commercial_ii integer not null, version integer not null, day_dosage_units double, primary key (therapy_ii, commercial_ii));
create table public.therapy_generic (therapy_ii integer not null, generic_ii integer not null, version integer not null, day_dosage_mg double, primary key (therapy_ii, generic_ii));
create table public.therapy_motivation (therapy_motivation_ii integer not null, version integer not null, value varchar(50) not null, primary key (therapy_motivation_ii));
create table public.user_attribute (user_attribute_ii integer not null, value_type_ii integer, uid varchar(50), name varchar(50), value varchar(100), data longvarchar, primary key (user_attribute_ii));
create table public.value_type (value_type_ii integer not null, version integer not null, description varchar(50) not null, minimum double, maximum double, multiple bit, primary key (value_type_ii));
create table public.viral_isolate (viral_isolate_ii integer not null, version integer not null, patient_ii integer not null, sample_id varchar(50), sample_date date, primary key (viral_isolate_ii));
alter table commercial_generic add constraint FK4E6E81E219F977A8 foreign key (generic_ii) references public.drug_generic;
alter table commercial_generic add constraint FK4E6E81E2A152DB96 foreign key (commercial_ii) references public.drug_commercial;
alter table public.aa_insertion add constraint FKE54E0D50CBB9BE97 foreign key (aa_sequence_ii) references public.aa_sequence;
alter table public.aa_mutation add constraint FK33795BE8CBB9BE97 foreign key (aa_sequence_ii) references public.aa_sequence;
alter table public.aa_sequence add constraint FK50514100608572E3 foreign key (nt_sequence_ii) references public.nt_sequence;
alter table public.aa_sequence add constraint FK5051410062F3E068 foreign key (protein_ii) references public.protein;
alter table public.analysis add constraint FKC2F032DC647DD22F foreign key (analysis_type_ii) references public.analysis_type;
alter table public.analysis_data add constraint FK6232DF2D46EE23D6 foreign key (analysis_ii) references public.analysis;
alter table public.attribute add constraint FKC7AA9C5FC38F0B foreign key (value_type_ii) references public.value_type;
alter table public.attribute add constraint FKC7AA9C6B7C6CBD foreign key (attribute_group_ii) references public.attribute_group;
alter table public.attribute_nominal_value add constraint FK558F63EB28201F88 foreign key (attribute_ii) references public.attribute;
alter table public.dataset add constraint FK5605B478F76A62F5 foreign key (uid) references public.settings_user;
alter table public.dataset_access add constraint FK1C0C870BB165C048 foreign key (dataset_ii) references public.dataset;
alter table public.dataset_access add constraint FK1C0C870BF76A62F5 foreign key (uid) references public.settings_user;
alter table public.drug_generic add constraint FK241E40388ED79C07 foreign key (drug_class_ii) references public.drug_class;
alter table public.nt_sequence add constraint FK161BA1A3C3F2CE1 foreign key (viral_isolate_ii) references public.viral_isolate;
alter table public.patient_attribute_value add constraint FKDA05D0D428201F88 foreign key (attribute_ii) references public.attribute;
alter table public.patient_attribute_value add constraint FKDA05D0D471F1932B foreign key (nominal_value_ii) references public.attribute_nominal_value;
alter table public.patient_attribute_value add constraint FKDA05D0D4CC6FF868 foreign key (patient_ii) references public.patient;
alter table public.patient_dataset add constraint FKE7A4713ECC6FF868 foreign key (patient_ii) references public.patient;
alter table public.patient_dataset add constraint FKE7A4713EB165C048 foreign key (dataset_ii) references public.dataset;
alter table public.query_definition add constraint FK9CE2A52AF76A62F5 foreign key (uid) references public.settings_user;
alter table public.query_definition_parameter add constraint FK5ADD66D46C0CA9F9 foreign key (query_definition_parameter_type_ii) references public.query_definition_parameter_type;
alter table public.query_definition_parameter add constraint FK5ADD66D468B43D19 foreign key (query_definition_ii) references public.query_definition;
alter table public.query_definition_run add constraint FK7384E9F668B43D19 foreign key (query_definition_ii) references public.query_definition;
alter table public.query_definition_run add constraint FK7384E9F6F76A62F5 foreign key (uid) references public.settings_user;
alter table public.query_definition_run_parameter add constraint FK34B91CA06634A1B0 foreign key (query_definition_parameter_ii) references public.query_definition_parameter;
alter table public.query_definition_run_parameter add constraint FK34B91CA0F97E9F30 foreign key (query_definition_run_ii) references public.query_definition_run;
alter table public.settings_user add constraint FKDBFE06679BD8A396 foreign key (test_ii) references public.test;
alter table public.settings_user add constraint FKDBFE0667B165C048 foreign key (dataset_ii) references public.dataset;
alter table public.test add constraint FK36449246EE23D6 foreign key (analysis_ii) references public.analysis;
alter table public.test add constraint FK36449291E3B81B foreign key (test_type_ii) references public.test_type;
alter table public.test_nominal_value add constraint FK37D6576191E3B81B foreign key (test_type_ii) references public.test_type;
alter table public.test_result add constraint FKEF1E986A9BD8A396 foreign key (test_ii) references public.test;
alter table public.test_result add constraint FKEF1E986A19F977A8 foreign key (generic_ii) references public.drug_generic;
alter table public.test_result add constraint FKEF1E986A608572E3 foreign key (nt_sequence_ii) references public.nt_sequence;
alter table public.test_result add constraint FKEF1E986ACC6FF868 foreign key (patient_ii) references public.patient;
alter table public.test_result add constraint FKEF1E986A4596F6EF foreign key (nominal_value_ii) references public.test_nominal_value;
alter table public.test_result add constraint FKEF1E986A3C3F2CE1 foreign key (viral_isolate_ii) references public.viral_isolate;
alter table public.test_type add constraint FKB9A90EC75FC38F0B foreign key (value_type_ii) references public.value_type;
alter table public.test_type add constraint FKB9A90EC7264DC6FB foreign key (test_object_ii) references public.test_object;
alter table public.therapy add constraint FKAF8F6C692F95783B foreign key (therapy_motivation_ii) references public.therapy_motivation;
alter table public.therapy add constraint FKAF8F6C69CC6FF868 foreign key (patient_ii) references public.patient;
alter table public.therapy_commercial add constraint FKE158F8E0AC63EEA8 foreign key (therapy_ii) references public.therapy;
alter table public.therapy_commercial add constraint FKE158F8E0A152DB96 foreign key (commercial_ii) references public.drug_commercial;
alter table public.therapy_generic add constraint FKE73DA401AC63EEA8 foreign key (therapy_ii) references public.therapy;
alter table public.therapy_generic add constraint FKE73DA40119F977A8 foreign key (generic_ii) references public.drug_generic;
alter table public.user_attribute add constraint FK5E2F8F285FC38F0B foreign key (value_type_ii) references public.value_type;
alter table public.user_attribute add constraint FK5E2F8F28F76A62F5 foreign key (uid) references public.settings_user;
alter table public.viral_isolate add constraint FK8C5625F6CC6FF868 foreign key (patient_ii) references public.patient;
create table dual_aa_sequence_aa_sequence_ii_seq (zero integer);
insert into dual_aa_sequence_aa_sequence_ii_seq values (0);
