create table regadbschema.aa_insertion (insertion_position smallint not null, aa_sequence_ii int not null, insertion_order smallint not null, version int not null, aa_insertion varchar(30) not null, nt_insertion_codon varchar(3) not null, primary key (insertion_position, aa_sequence_ii, insertion_order));
create table regadbschema.aa_mutation (mutation_position smallint not null, aa_sequence_ii int not null, version int not null, aa_reference varchar(1) not null, aa_mutation varchar(30) null, nt_reference_codon varchar(3) not null, nt_mutation_codon varchar(3) null, primary key (mutation_position, aa_sequence_ii));
create table regadbschema.aa_sequence (aa_sequence_ii int identity not null, version int not null, nt_sequence_ii int not null, protein_ii int not null, first_aa_pos smallint not null, last_aa_pos smallint not null, primary key (aa_sequence_ii));
create table regadbschema.analysis (analysis_ii int identity not null, analysis_type_ii int not null, url varchar(100) null, account varchar(50) null, password varchar(100) null, baseinputfile varchar(50) null, baseoutputfile varchar(50) null, service_name varchar(100) null, dataoutputfile varchar(50) null, primary key (analysis_ii));
create table regadbschema.analysis_data (analysis_data_ii int identity not null, analysis_ii int not null, name varchar(50) null, data varbinary(MAX) null, mimetype varchar(50) not null, primary key (analysis_data_ii));
create table regadbschema.analysis_type (analysis_type_ii int identity not null, type varchar(50) null, primary key (analysis_type_ii));
create table regadbschema.attribute (attribute_ii int identity not null, version int not null, value_type_ii int null, attribute_group_ii int null, name varchar(50) not null, validation_string varchar(100) null, primary key (attribute_ii));
create table regadbschema.attribute_group (attribute_group_ii int identity not null, version int not null, group_name varchar(50) null, primary key (attribute_group_ii));
create table regadbschema.attribute_nominal_value (nominal_value_ii int identity not null, version int not null, attribute_ii int not null, value varchar(100) not null, primary key (nominal_value_ii));
create table regadbschema.combined_query (combined_query_ii int identity not null, name varchar(50) not null, primary key (combined_query_ii));
create table regadbschema.combined_query_definition (combined_query_ii int not null, query_definition_ii int not null, number int not null, name varchar(50) null, primary key (combined_query_ii, query_definition_ii));
create table regadbschema.commercial_generic (generic_ii int not null, commercial_ii int not null, primary key (commercial_ii, generic_ii));
create table regadbschema.dataset (dataset_ii int identity not null, version int not null, uid varchar(50) not null, description varchar(50) not null, creation_date datetime not null, closed_date datetime null, revision int null, primary key (dataset_ii));
create table regadbschema.dataset_access (uid varchar(50) not null, dataset_ii int not null, version int not null, permissions int not null, provider varchar(50) not null, primary key (uid, dataset_ii));
create table regadbschema.drug_class (drug_class_ii int identity not null, version int not null, class_id varchar(10) not null, class_name varchar(100) not null, resistance_table_order int null, primary key (drug_class_ii));
create table regadbschema.drug_commercial (commercial_ii int identity not null, version int not null, name varchar(100) not null, atc_code varchar(50) null, primary key (commercial_ii));
create table regadbschema.drug_generic (generic_ii int identity not null, version int not null, drug_class_ii int not null, generic_id varchar(10) not null, generic_name varchar(50) not null, resistance_table_order int null, atc_code varchar(50) null, primary key (generic_ii));
create table regadbschema.event (event_ii int identity not null, version int not null, value_type_ii int null, name varchar(50) not null, primary key (event_ii));
create table regadbschema.event_nominal_value (nominal_value_ii int identity not null, version int not null, event_ii int not null, value varchar(500) not null, primary key (nominal_value_ii));
create table regadbschema.genome (genome_ii int identity not null, version int not null, organism_name varchar(50) not null, organism_description varchar(500) not null, genbank_number varchar(50) null, primary key (genome_ii));
create table regadbschema.genome_drug_generic (genome_ii int not null, generic_ii int not null, primary key (generic_ii, genome_ii));
create table regadbschema.nt_sequence (nt_sequence_ii int identity not null, version int not null, viral_isolate_ii int not null, label varchar(50) null, sequence_date datetime null, nucleotides text null, aligned tinyint null, primary key (nt_sequence_ii));
create table regadbschema.open_reading_frame (open_reading_frame_ii int identity not null, version int not null, genome_ii int not null, name varchar(50) not null, description varchar(500) not null, reference_sequence text not null, primary key (open_reading_frame_ii));
create table regadbschema.patient (patient_ii int identity not null, version int not null, patient_id varchar(50) not null, primary key (patient_ii));
create table regadbschema.patient_attribute_value (patient_attribute_value_ii int identity not null, version int not null, attribute_ii int not null, patient_ii int not null, nominal_value_ii int null, value varchar(100) null, primary key (patient_attribute_value_ii));
create table regadbschema.patient_dataset (dataset_ii int not null, patient_ii int not null, primary key (dataset_ii, patient_ii));
create table regadbschema.patient_event_value (patient_event_value_ii int identity not null, version int not null, patient_ii int not null, nominal_value_ii int null, event_ii int not null, value text null, start_date datetime null, end_date datetime null, primary key (patient_event_value_ii));
create table regadbschema.protein (protein_ii int identity not null, version int not null, open_reading_frame_ii int not null, abbreviation varchar(50) not null, full_name varchar(50) null, start_position int not null, stop_position int not null, primary key (protein_ii));
create table regadbschema.query_definition (query_definition_ii int identity not null, uid varchar(50) null, name varchar(50) null, description text null, query text null, query_type_ii int not null, post_processing_script varbinary(MAX) null, primary key (query_definition_ii));
create table regadbschema.query_definition_parameter (query_definition_parameter_ii int identity not null, query_definition_parameter_type_ii int null, query_definition_ii int null, name varchar(50) null, primary key (query_definition_parameter_ii));
create table regadbschema.query_definition_parameter_type (query_definition_parameter_type_ii int identity not null, name varchar(100) not null, id int not null, primary key (query_definition_parameter_type_ii));
create table regadbschema.query_definition_run (query_definition_run_ii int identity not null, query_definition_ii int null, uid varchar(50) null, startdate datetime null, enddate datetime null, status int null, name varchar(100) not null, result varchar(100) null, primary key (query_definition_run_ii));
create table regadbschema.query_definition_run_parameter (query_definition_run_parameter_ii int identity not null, query_definition_parameter_ii int null, query_definition_run_ii int null, value varchar(50) null, primary key (query_definition_run_parameter_ii));
create table regadbschema.resistance_interpretation_template (template_ii int identity not null, name varchar(100) null, document varbinary(MAX) null, filename varchar(100) null, primary key (template_ii));
create table regadbschema.settings_user (uid varchar(50) not null, version int not null, test_ii int null, dataset_ii int null, chart_width int not null, chart_height int not null, password varchar(50) null, email varchar(100) null, first_name varchar(50) null, last_name varchar(50) null, role varchar(50) null, primary key (uid));
create table regadbschema.splicing_position (splicing_position_ii int identity not null, version int not null, protein_ii int not null, nt_position int not null, primary key (splicing_position_ii));
create table regadbschema.test (test_ii int identity not null, version int not null, analysis_ii int null, test_type_ii int not null, description varchar(50) not null, primary key (test_ii));
create table regadbschema.test_nominal_value (nominal_value_ii int identity not null, version int not null, test_type_ii int not null, value varchar(100) not null, primary key (nominal_value_ii));
create table regadbschema.test_object (test_object_ii int identity not null, version int not null, description varchar(50) not null, test_object_id int null, primary key (test_object_ii));
create table regadbschema.test_result (test_result_ii int identity not null, version int not null, test_ii int not null, generic_ii int null, viral_isolate_ii int null, therapy_ii int null, nominal_value_ii int null, patient_ii int null, nt_sequence_ii int null, value varchar(50) null, test_date datetime null, sample_id varchar(50) null, data varbinary(MAX) null, primary key (test_result_ii));
create table regadbschema.test_type (test_type_ii int identity not null, version int not null, value_type_ii int null, genome_ii int null, test_object_ii int not null, description varchar(50) not null, primary key (test_type_ii));
create table regadbschema.therapy (therapy_ii int identity not null, version int not null, therapy_motivation_ii int null, patient_ii int not null, start_date datetime not null, stop_date datetime null, comment varchar(200) null, primary key (therapy_ii));
create table regadbschema.therapy_commercial (therapy_ii int not null, commercial_ii int not null, version int not null, day_dosage_units double precision null, placebo tinyint not null, blind tinyint not null, frequency numeric(19,0) null, primary key (therapy_ii, commercial_ii));
create table regadbschema.therapy_generic (therapy_ii int not null, generic_ii int not null, version int not null, day_dosage_mg double precision null, placebo tinyint not null, blind tinyint not null, frequency numeric(19,0) null, primary key (therapy_ii, generic_ii));
create table regadbschema.therapy_motivation (therapy_motivation_ii int identity not null, version int not null, value varchar(50) not null, primary key (therapy_motivation_ii));
create table regadbschema.user_attribute (user_attribute_ii int identity not null, value_type_ii int null, uid varchar(50) null, name varchar(50) null, value varchar(100) null, data varbinary(MAX) null, primary key (user_attribute_ii));
create table regadbschema.value_type (value_type_ii int identity not null, version int not null, description varchar(50) not null, minimum double precision null, maximum double precision null, multiple tinyint null, primary key (value_type_ii));
create table regadbschema.viral_isolate (viral_isolate_ii int identity not null, version int not null, patient_ii int not null, sample_id varchar(50) null, sample_date datetime null, genome_ii int null, primary key (viral_isolate_ii));
alter table regadbschema.aa_insertion add constraint FKE54E0D50CBB9BE97 foreign key (aa_sequence_ii) references regadbschema.aa_sequence;
alter table regadbschema.aa_mutation add constraint FK33795BE8CBB9BE97 foreign key (aa_sequence_ii) references regadbschema.aa_sequence;
alter table regadbschema.aa_sequence add constraint FK50514100608572E3 foreign key (nt_sequence_ii) references regadbschema.nt_sequence;
alter table regadbschema.aa_sequence add constraint FK5051410062F3E068 foreign key (protein_ii) references regadbschema.protein;
alter table regadbschema.analysis add constraint FKC2F032DC647DD22F foreign key (analysis_type_ii) references regadbschema.analysis_type;
alter table regadbschema.analysis_data add constraint FK6232DF2D46EE23D6 foreign key (analysis_ii) references regadbschema.analysis;
alter table regadbschema.attribute add constraint FKC7AA9C5FC38F0B foreign key (value_type_ii) references regadbschema.value_type;
alter table regadbschema.attribute add constraint FKC7AA9C6B7C6CBD foreign key (attribute_group_ii) references regadbschema.attribute_group;
alter table regadbschema.attribute_nominal_value add constraint FK558F63EB28201F88 foreign key (attribute_ii) references regadbschema.attribute;
alter table regadbschema.combined_query_definition add constraint FKA51227245D802F7D foreign key (combined_query_ii) references regadbschema.combined_query;
alter table regadbschema.combined_query_definition add constraint FKA512272468B43D19 foreign key (query_definition_ii) references regadbschema.query_definition;
alter table regadbschema.commercial_generic add constraint FK4E6E81E219F977A8 foreign key (generic_ii) references regadbschema.drug_generic;
alter table regadbschema.commercial_generic add constraint FK4E6E81E2A152DB96 foreign key (commercial_ii) references regadbschema.drug_commercial;
alter table regadbschema.dataset add constraint FK5605B478F76A62F5 foreign key (uid) references regadbschema.settings_user;
alter table regadbschema.dataset_access add constraint FK1C0C870BB165C048 foreign key (dataset_ii) references regadbschema.dataset;
alter table regadbschema.dataset_access add constraint FK1C0C870BF76A62F5 foreign key (uid) references regadbschema.settings_user;
alter table regadbschema.drug_generic add constraint FK241E40388ED79C07 foreign key (drug_class_ii) references regadbschema.drug_class;
alter table regadbschema.event add constraint FK5C6729A5FC38F0B foreign key (value_type_ii) references regadbschema.value_type;
alter table regadbschema.event_nominal_value add constraint FK7D59576933594348 foreign key (event_ii) references regadbschema.event;
alter table regadbschema.genome_drug_generic add constraint FKCA02968019F977A8 foreign key (generic_ii) references regadbschema.drug_generic;
alter table regadbschema.genome_drug_generic add constraint FKCA0296805A4F23B6 foreign key (genome_ii) references regadbschema.genome;
alter table regadbschema.nt_sequence add constraint FK161BA1A3C3F2CE1 foreign key (viral_isolate_ii) references regadbschema.viral_isolate;
alter table regadbschema.open_reading_frame add constraint FK6BDEF0C55A4F23B6 foreign key (genome_ii) references regadbschema.genome;
alter table regadbschema.patient_attribute_value add constraint FKDA05D0D428201F88 foreign key (attribute_ii) references regadbschema.attribute;
alter table regadbschema.patient_attribute_value add constraint FKDA05D0D471F1932B foreign key (nominal_value_ii) references regadbschema.attribute_nominal_value;
alter table regadbschema.patient_attribute_value add constraint FKDA05D0D4CC6FF868 foreign key (patient_ii) references regadbschema.patient;
alter table regadbschema.patient_dataset add constraint FKE7A4713EB165C048 foreign key (dataset_ii) references regadbschema.dataset;
alter table regadbschema.patient_dataset add constraint FKE7A4713ECC6FF868 foreign key (patient_ii) references regadbschema.patient;
alter table regadbschema.patient_event_value add constraint FK11B8755233594348 foreign key (event_ii) references regadbschema.event;
alter table regadbschema.patient_event_value add constraint FK11B875526A5E9AA9 foreign key (nominal_value_ii) references regadbschema.event_nominal_value;
alter table regadbschema.patient_event_value add constraint FK11B87552CC6FF868 foreign key (patient_ii) references regadbschema.patient;
alter table regadbschema.protein add constraint FKED94D783E79F51C foreign key (open_reading_frame_ii) references regadbschema.open_reading_frame;
alter table regadbschema.query_definition add constraint FK9CE2A52AF76A62F5 foreign key (uid) references regadbschema.settings_user;
alter table regadbschema.query_definition_parameter add constraint FK5ADD66D468B43D19 foreign key (query_definition_ii) references regadbschema.query_definition;
alter table regadbschema.query_definition_parameter add constraint FK5ADD66D46C0CA9F9 foreign key (query_definition_parameter_type_ii) references regadbschema.query_definition_parameter_type;
alter table regadbschema.query_definition_run add constraint FK7384E9F668B43D19 foreign key (query_definition_ii) references regadbschema.query_definition;
alter table regadbschema.query_definition_run add constraint FK7384E9F6F76A62F5 foreign key (uid) references regadbschema.settings_user;
alter table regadbschema.query_definition_run_parameter add constraint FK34B91CA06634A1B0 foreign key (query_definition_parameter_ii) references regadbschema.query_definition_parameter;
alter table regadbschema.query_definition_run_parameter add constraint FK34B91CA0F97E9F30 foreign key (query_definition_run_ii) references regadbschema.query_definition_run;
alter table regadbschema.settings_user add constraint FKDBFE06679BD8A396 foreign key (test_ii) references regadbschema.test;
alter table regadbschema.settings_user add constraint FKDBFE0667B165C048 foreign key (dataset_ii) references regadbschema.dataset;
alter table regadbschema.splicing_position add constraint FK52F9C66F62F3E068 foreign key (protein_ii) references regadbschema.protein;
alter table regadbschema.test add constraint FK36449246EE23D6 foreign key (analysis_ii) references regadbschema.analysis;
alter table regadbschema.test add constraint FK36449291E3B81B foreign key (test_type_ii) references regadbschema.test_type;
alter table regadbschema.test_nominal_value add constraint FK37D6576191E3B81B foreign key (test_type_ii) references regadbschema.test_type;
alter table regadbschema.test_result add constraint FKEF1E986A19F977A8 foreign key (generic_ii) references regadbschema.drug_generic;
alter table regadbschema.test_result add constraint FKEF1E986A3C3F2CE1 foreign key (viral_isolate_ii) references regadbschema.viral_isolate;
alter table regadbschema.test_result add constraint FKEF1E986A4596F6EF foreign key (nominal_value_ii) references regadbschema.test_nominal_value;
alter table regadbschema.test_result add constraint FKEF1E986A608572E3 foreign key (nt_sequence_ii) references regadbschema.nt_sequence;
alter table regadbschema.test_result add constraint FKEF1E986A9BD8A396 foreign key (test_ii) references regadbschema.test;
alter table regadbschema.test_result add constraint FKEF1E986ACC6FF868 foreign key (patient_ii) references regadbschema.patient;
alter table regadbschema.test_result add constraint FKEF1E986ACC6FF869 foreign key (therapy_ii) references regadbschema.therapy;
alter table regadbschema.test_type add constraint FKB9A90EC7264DC6FB foreign key (test_object_ii) references regadbschema.test_object;
alter table regadbschema.test_type add constraint FKB9A90EC75A4F23B6 foreign key (genome_ii) references regadbschema.genome;
alter table regadbschema.test_type add constraint FKB9A90EC75FC38F0B foreign key (value_type_ii) references regadbschema.value_type;
alter table regadbschema.therapy add constraint FKAF8F6C692F95783B foreign key (therapy_motivation_ii) references regadbschema.therapy_motivation;
alter table regadbschema.therapy add constraint FKAF8F6C69CC6FF868 foreign key (patient_ii) references regadbschema.patient;
alter table regadbschema.therapy_commercial add constraint FKE158F8E0A152DB96 foreign key (commercial_ii) references regadbschema.drug_commercial;
alter table regadbschema.therapy_commercial add constraint FKE158F8E0AC63EEA8 foreign key (therapy_ii) references regadbschema.therapy;
alter table regadbschema.therapy_generic add constraint FKE73DA40119F977A8 foreign key (generic_ii) references regadbschema.drug_generic;
alter table regadbschema.therapy_generic add constraint FKE73DA401AC63EEA8 foreign key (therapy_ii) references regadbschema.therapy;
alter table regadbschema.user_attribute add constraint FK5E2F8F285FC38F0B foreign key (value_type_ii) references regadbschema.value_type;
alter table regadbschema.user_attribute add constraint FK5E2F8F28F76A62F5 foreign key (uid) references regadbschema.settings_user;
alter table regadbschema.viral_isolate add constraint FK8C5625F65A4F23B6 foreign key (genome_ii) references regadbschema.genome;
alter table regadbschema.viral_isolate add constraint FK8C5625F6CC6FF868 foreign key (patient_ii) references regadbschema.patient;
create index aa_sequence_nt_sequence_ii_idx on regadbschema.aa_sequence (nt_sequence_ii);
create index aa_sequence_protein_ii_idx on regadbschema.aa_sequence (protein_ii);
create index analysis_analysis_type_ii_idx on regadbschema.analysis (analysis_type_ii);
create index analysis_data_analysis_ii_idx on regadbschema.analysis_data (analysis_ii);
create index attribute_attribute_group_ii_idx on regadbschema.attribute (attribute_group_ii);
create index attribute_nominal_value_attribute_ii_idx on regadbschema.attribute_nominal_value (attribute_ii);
create index attribute_value_type_ii_idx on regadbschema.attribute (value_type_ii);
create index combined_query_definition_combined_query_ii_idx on regadbschema.combined_query_definition (combined_query_ii);
create index combined_query_definition_query_definition_ii_idx on regadbschema.combined_query_definition (query_definition_ii);
create index dataset_uid_idx on regadbschema.dataset (uid);
create index drug_generic_drug_class_ii_idx on regadbschema.drug_generic (drug_class_ii);
create index event_nominal_value_event_ii_idx on regadbschema.event_nominal_value (event_ii);
create index event_value_type_ii_idx on regadbschema.event (value_type_ii);
create index nt_sequence_viral_isolate_ii_idx on regadbschema.nt_sequence (viral_isolate_ii);
create index open_reading_frame_genome_ii_idx on regadbschema.open_reading_frame (genome_ii);
create index patient_attribute_value_attribute_ii_idx on regadbschema.patient_attribute_value (attribute_ii);
create index patient_attribute_value_nominal_value_ii_idx on regadbschema.patient_attribute_value (nominal_value_ii);
create index patient_attribute_value_patient_ii_idx on regadbschema.patient_attribute_value (patient_ii);
create index patient_event_value_event_ii_idx on regadbschema.patient_event_value (event_ii);
create index patient_event_value_nominal_value_ii_idx on regadbschema.patient_event_value (nominal_value_ii);
create index patient_event_value_patient_ii_idx on regadbschema.patient_event_value (patient_ii);
create index protein_open_reading_frame_ii_idx on regadbschema.protein (open_reading_frame_ii);
create index query_definition_parameter_query_definition_ii_idx on regadbschema.query_definition_parameter (query_definition_ii);
create index query_definition_parameter_query_definition_parameter_type_ii_idx on regadbschema.query_definition_parameter (query_definition_parameter_type_ii);
create index query_definition_run_parameter_query_definition_parameter_ii_idx on regadbschema.query_definition_run_parameter (query_definition_parameter_ii);
create index query_definition_run_parameter_query_definition_run_ii_idx on regadbschema.query_definition_run_parameter (query_definition_run_ii);
create index query_definition_run_query_definition_ii_idx on regadbschema.query_definition_run (query_definition_ii);
create index query_definition_run_uid_idx on regadbschema.query_definition_run (uid);
create index query_definition_uid_idx on regadbschema.query_definition (uid);
create index settings_user_dataset_ii_idx on regadbschema.settings_user (dataset_ii);
create index settings_user_test_ii_idx on regadbschema.settings_user (test_ii);
create index splicing_position_protein_ii_idx on regadbschema.splicing_position (protein_ii);
create index test_analysis_ii_idx on regadbschema.test (analysis_ii);
create index test_nominal_value_test_type_ii_idx on regadbschema.test_nominal_value (test_type_ii);
create index test_result_generic_ii_idx on regadbschema.test_result (generic_ii);
create index test_result_nominal_value_ii_idx on regadbschema.test_result (nominal_value_ii);
create index test_result_nt_sequence_ii_idx on regadbschema.test_result (nt_sequence_ii);
create index test_result_patient_ii_idx on regadbschema.test_result (patient_ii);
create index test_result_test_ii_idx on regadbschema.test_result (test_ii);
create index test_result_viral_isolate_ii_idx on regadbschema.test_result (viral_isolate_ii);
create index test_result_therapy_ii_idx on regadbschema.test_result (therapy_ii);
create index test_test_type_ii_idx on regadbschema.test (test_type_ii);
create index test_type_genome_ii_idx on regadbschema.test_type (genome_ii);
create index test_type_test_object_ii_idx on regadbschema.test_type (test_object_ii);
create index test_type_value_type_ii_idx on regadbschema.test_type (value_type_ii);
create index therapy_patient_ii_idx on regadbschema.therapy (patient_ii);
create index therapy_therapy_motivation_ii_idx on regadbschema.therapy (therapy_motivation_ii);
create index user_attribute_uid_idx on regadbschema.user_attribute (uid);
create index user_attribute_value_type_ii_idx on regadbschema.user_attribute (value_type_ii);
create index viral_isolate_genome_ii_idx on regadbschema.viral_isolate (genome_ii);
create index viral_isolate_patient_ii_idx on regadbschema.viral_isolate (patient_ii);
